# 9 WorkFlow Analista Senior

### 9.5 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
enriquecer
<br>El Analista Sr corre sus scripts en máquinas virtuales de al menos 128 GB de RAM en Toronto, creando una virtual machine para cada corrida.
<br>Estas virtual machines se auto-suicidarán a los 30 minutos de haber terminado de procesar.

## 9.7  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 24 21:26:10 2025"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  656928 35.1 1439380    76.9 1431350  76.5
Vcells 1225095  9.4 8388608    64.0 1924965  14.7

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table

Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: ‘R.oo’


The following object is masked from ‘package:R.methodsS3’:

    throw


The following objects are masked from ‘package:methods’:

    getClasses, getMethods


The following objects are masked from ‘package:base’:

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: ‘R.utils’


The following object is masked from ‘package:utils’:

    timestamp


The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
PARAM <- list()
PARAM$semilla_primigenia <- 888889

PARAM$experimento <- 950111
PARAM$dataset <- "analistasr_competencia_2025.csv.gz"

#### Carpeta del Experimento

In [5]:
# carpeta de trabajo

setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("WF", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [6]:
# Función para enviar mensajes a ntfy
notificar <- function(mensaje) {
  system(sprintf('curl -d "%s" https://ntfy.sh/boruta', mensaje))
}

In [7]:
notificar(paste0("🏁 ARRRRRANCA la Noteboooook"))

### 9.7.1   Preprocesamiento del dataset

#### 9.7.1.1  DT incorporar dataset

In [8]:
# lectura del dataset
dataset <- fread(paste0("/content/datasets/", PARAM$dataset))

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

#### 9.7.1.4  FEhist Feature Engineering historico

El Fature Engineering Histórico es la etapa que más aporta a la ganancia final, ya que enriquece cada registro del dataset con su historia.

Para cada campo del dataset original (*)
se crean lo siguientes campos de a partir de la historia
* lag1  lags de orden 1
* delta1  =  valor actual - lag1
* lag2  lags de orden 2
* delta2  = valor actual - lag2


(*) Excepto para los campos  <numero_de_cliente,  foto_mes,  clase_ternaria>

In [9]:
if( !require("Rcpp")) install.packages("Rcpp", repos = "http://cran.us.r-project.org")
require("Rcpp")

Loading required package: Rcpp

In [10]:
# se calculan para los 6 meses previos el minimo, maximo y
#  tendencia calculada con cuadrados minimos
# la formula de calculo de la tendencia puede verse en
#  https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Introductory_Statistics_(Shafer_and_Zhang)/10%3A_Correlation_and_Regression/10.04%3A_The_Least_Squares_Regression_Line
# para la maxíma velocidad esta funcion esta escrita en lenguaje C,
# y no en la porqueria de R o Python

cppFunction("NumericVector fhistC(NumericVector pcolumna, IntegerVector pdesde )
{
  /* Aqui se cargan los valores para la regresion */
  double  x[100] ;
  double  y[100] ;

  int n = pcolumna.size();
  NumericVector out( 5*n );

  for(int i = 0; i < n; i++)
  {
    //lag
    if( pdesde[i]-1 < i )  out[ i + 4*n ]  =  pcolumna[i-1] ;
    else                   out[ i + 4*n ]  =  NA_REAL ;


    int  libre    = 0 ;
    int  xvalor   = 1 ;

    for( int j= pdesde[i]-1;  j<=i; j++ )
    {
       double a = pcolumna[j] ;

       if( !R_IsNA( a ) )
       {
          y[ libre ]= a ;
          x[ libre ]= xvalor ;
          libre++ ;
       }

       xvalor++ ;
    }

    /* Si hay al menos dos valores */
    if( libre > 1 )
    {
      double  xsum  = x[0] ;
      double  ysum  = y[0] ;
      double  xysum = xsum * ysum ;
      double  xxsum = xsum * xsum ;
      double  vmin  = y[0] ;
      double  vmax  = y[0] ;

      for( int h=1; h<libre; h++)
      {
        xsum  += x[h] ;
        ysum  += y[h] ;
        xysum += x[h]*y[h] ;
        xxsum += x[h]*x[h] ;

        if( y[h] < vmin )  vmin = y[h] ;
        if( y[h] > vmax )  vmax = y[h] ;
      }

      out[ i ]  =  (libre*xysum - xsum*ysum)/(libre*xxsum -xsum*xsum) ;
      out[ i + n ]    =  vmin ;
      out[ i + 2*n ]  =  vmax ;
      out[ i + 3*n ]  =  ysum / libre ;
    }
    else
    {
      out[ i       ]  =  NA_REAL ;
      out[ i + n   ]  =  NA_REAL ;
      out[ i + 2*n ]  =  NA_REAL ;
      out[ i + 3*n ]  =  NA_REAL ;
    }
  }

  return  out;
}")

In [11]:
# calcula la tendencia de las variables cols de los ultimos 6 meses
# la tendencia es la pendiente de la recta que ajusta por cuadrados minimos
# La funcionalidad de ratioavg es autoria de  Daiana Sparta,  UAustral  2021

TendenciaYmuchomas <- function(
    dataset, cols, ventana = 6, tendencia = TRUE,
    minimo = TRUE, maximo = TRUE, promedio = TRUE,
    ratioavg = FALSE, ratiomax = FALSE) {
  gc(verbose= FALSE)
  # Esta es la cantidad de meses que utilizo para la historia
  ventana_regresion <- ventana

  last <- nrow(dataset)

  # creo el vector_desde que indica cada ventana
  # de esta forma se acelera el procesamiento ya que lo hago una sola vez
  vector_ids <- dataset[ , numero_de_cliente ]

  vector_desde <- seq(
    -ventana_regresion + 2,
    nrow(dataset) - ventana_regresion + 1
  )

  vector_desde[1:ventana_regresion] <- 1

  for (i in 2:last) {
    if (vector_ids[i - 1] != vector_ids[i]) {
      vector_desde[i] <- i
    }
  }
  for (i in 2:last) {
    if (vector_desde[i] < vector_desde[i - 1]) {
      vector_desde[i] <- vector_desde[i - 1]
    }
  }

  for (campo in cols) {
    nueva_col <- fhistC(dataset[, get(campo)], vector_desde)

    if (tendencia) {
      dataset[, paste0(campo, "_tend", ventana) :=
        nueva_col[(0 * last + 1):(1 * last)]]
    }

    if (minimo) {
      dataset[, paste0(campo, "_min", ventana) :=
        nueva_col[(1 * last + 1):(2 * last)]]
    }

    if (maximo) {
      dataset[, paste0(campo, "_max", ventana) :=
        nueva_col[(2 * last + 1):(3 * last)]]
    }

    if (promedio) {
      dataset[, paste0(campo, "_avg", ventana) :=
        nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratioavg) {
      dataset[, paste0(campo, "_ratioavg", ventana) :=
        get(campo) / nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratiomax) {
      dataset[, paste0(campo, "_ratiomax", ventana) :=
        get(campo) / nueva_col[(2 * last + 1):(3 * last)]]
    }
  }
}

In [12]:
# Feature Engineering Historico

setorder(dataset, numero_de_cliente, foto_mes)

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente", "foto_mes", "clase_ternaria")
) )

# https://rdrr.io/cran/data.table/man/shift.html

# lags de orden 1
dataset[,
    paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# lags de orden 2
dataset[,
    paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
    by = numero_de_cliente,
    .SDcols = cols_lagueables
]

# agrego los delta lags
for (vcol in cols_lagueables)
{
    dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
    dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
}

In [13]:
# parametros de Feature Engineering Historico de Tendencias
PARAM$FE_hist$Tendencias$run <- TRUE
PARAM$FE_hist$Tendencias$ventana <- 6
PARAM$FE_hist$Tendencias$tendencia <- TRUE
PARAM$FE_hist$Tendencias$minimo <- FALSE
PARAM$FE_hist$Tendencias$maximo <- FALSE
PARAM$FE_hist$Tendencias$promedio <- FALSE
PARAM$FE_hist$Tendencias$ratioavg <- FALSE
PARAM$FE_hist$Tendencias$ratiomax <- FALSE

In [14]:
cols_lagueables <- intersect(cols_lagueables, colnames(dataset))
setorder(dataset, numero_de_cliente, foto_mes)

if( PARAM$FE_hist$Tendencias$run) {
    TendenciaYmuchomas(dataset,
    cols = cols_lagueables,
    ventana = PARAM$FE_hist$Tendencias$ventana, # 6 meses de historia
    tendencia = PARAM$FE_hist$Tendencias$tendencia,
    minimo = PARAM$FE_hist$Tendencias$minimo,
    maximo = PARAM$FE_hist$Tendencias$maximo,
    promedio = PARAM$FE_hist$Tendencias$promedio,
    ratioavg = PARAM$FE_hist$Tendencias$ratioavg,
    ratiomax = PARAM$FE_hist$Tendencias$ratiomax
  )
}

Verificacion de los campos recien creados

In [15]:
ncol(dataset)
colnames(dataset)

[1] 915

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "mrentabilidad"
  [9] "mrentabilidad_annual"
 [10] "mcomisiones"
 [11] "mactivos_margen"
 [12] "mpasivos_margen"
 [13] "cproductos"
 [14] "tcuentas"
 [15] "ccuenta_corriente"
 [16] "mcuenta_corriente_adicional"
 [17] "mcuenta_corriente"
 [18] "ccaja_ahorro"
 [19] "mcaja_ahorro"
 [20] "mcaja_ahorro_adicional"
 [21] "mcaja_ahorro_dolares"
 [22] "cdescubierto_preacordado"
 [23] "mcuentas_saldo"
 [24] "ctarjeta_debito"
 [25] "ctarjeta_debito_transacciones"
 [26] "mautoservicio"
 [27] "ctarjeta_visa"
 [28] "ctarjeta_visa_transacciones"
 [29] "mtarjeta_visa_consumo"
 [30] "ctarjeta_master"
 [31] "ctarjeta_master_transacciones"
 [32] "mtarjeta_master_consumo"
 [33] "cprestamos_personales"
 [34] "mprestamos_personales"
 [35] "cprestamos_prendarios"
 [36] "mprestamos_prendarios"
 [37] "cprestamos_hipotecarios"
 [38] "mprestamos_hipotecarios"
 [39] "cplazo_fijo"
 [40] "mplazo_fijo_dolares"
 [41] "mplazo_fijo_pesos"
 [42] "cinversion1"
 [43] "minversion1_pesos"
 [44] "minversion1_dolares"
 [45] "cinversion2"
 [46] "minversion2"
 [47] "cseguro_vida"
 [48] "cseguro_auto"
 [49] "cseguro_vivienda"
 [50] "cseguro_accidentes_personales"
 [51] "ccaja_seguridad"
 [52] "cpayroll_trx"
 [53] "mpayroll"
 [54] "mpayroll2"
 [55] "cpayroll2_trx"
 [56] "ccuenta_debitos_automaticos"
 [57] "mcuenta_debitos_automaticos"
 [58] "ctarjeta_visa_debitos_automaticos"
 [59] "mttarjeta_visa_debitos_automaticos"
 [60] "ctarjeta_master_debitos_automaticos"
 [61] "mttarjeta_master_debitos_automaticos"
 [62] "cpagodeservicios"
 [63] "mpagodeservicios"
 [64] "cpagomiscuentas"
 [65] "mpagomiscuentas"
 [66] "ccajeros_propios_descuentos"
 [67] "mcajeros_propios_descuentos"
 [68] "ctarjeta_visa_descuentos"
 [69] "mtarjeta_visa_descuentos"
 [70] "ctarjeta_master_descuentos"
 [71] "mtarjeta_master_descuentos"
 [72] "ccomisiones_mantenimiento"
 [73] "mcomisiones_mantenimiento"
 [74] "ccomisiones_otras"
 [75] "mcomisiones_otras"
 [76] "cforex"
 [77] "cforex_buy"
 [78] "mforex_buy"
 [79] "cforex_sell"
 [80] "mforex_sell"
 [81] "ctransferencias_recibidas"
 [82] "mtransferencias_recibidas"
 [83] "ctransferencias_emitidas"
 [84] "mtransferencias_emitidas"
 [85] "cextraccion_autoservicio"
 [86] "mextraccion_autoservicio"
 [87] "ccheques_depositados"
 [88] "mcheques_depositados"
 [89] "ccheques_emitidos"
 [90] "mcheques_emitidos"
 [91] "ccheques_depositados_rechazados"
 [92] "mcheques_depositados_rechazados"
 [93] "ccheques_emitidos_rechazados"
 [94] "mcheques_emitidos_rechazados"
 [95] "tcallcenter"
 [96] "ccallcenter_transacciones"
 [97] "thomebanking"
 [98] "chomebanking_transacciones"
 [99] "ccajas_transacciones"
[100] "ccajas_consultas"
[101] "ccajas_depositos"
[102] "ccajas_extracciones"
[103] "ccajas_otras"
[104] "catm_trx"
[105] "matm"
[106] "catm_trx_other"
[107] "matm_other"
[108] "ctrx_quarter"
[109] "tmobile_app"
[110] "cmobile_app_trx"
[111] "Master_delinquency"
[112] "Master_status"
[113] "Master_mfinanciacion_limite"
[114] "Master_Fvencimiento"
[115] "Master_Finiciomora"
[116] "Master_msaldototal"
[117] "Master_msaldopesos"
[118] "Master_msaldodolares"
[119] "Master_mconsumospesos"
[120] "Master_mconsumosdolares"
[121] "Master_mlimitecompra"
[122] "Master_madelantopesos"
[123] "Master_madelantodolares"
[124] "Master_fultimo_cierre"
[125] "Master_mpagado"
[126] "Master_mpagospesos"
[127] "Master_mpagosdolares"
[128] "Master_fechaalta"
[129] "Master_mconsumototal"
[130] "Master_cconsumos"
[131] "Master_cadelantosefectivo"
[132] "Master_mpagominimo"
[133] "Visa_delinquency"
[134] "Visa_status"
[135] "Visa_mfinanciacion_limite"
[136] "Visa_Fvencimiento"
[137] "Visa_Finiciomora"
[138] "Visa_msaldototal"
[139] "Visa_msaldopesos"
[140] "Visa_msaldodolares"
[141] "Visa_mconsumospesos"
[142] "Visa_mconsumosdolares"
[143] "Visa_mlimitecompra"
[144] "Visa_madelantopesos"
[145] "Visa_madelantodolares"
[146] "Visa_fultimo_cierre"
[147] "Visa_mpagado"
[148] "Visa_mpagospesos"
[149] "Visa_mpagosdolares"
[150] "Visa_fechaalta"
[151] "Visa_mconsumototal"
[152] "Visa_cconsumos"
[153] "Visa_cadelantosefectivo"
[154] "Visa_mpagominimo"
[155] "clase_ternaria"
[156] "active_quarter_lag1"
[157] "cliente_vip_lag1"
[158] "internet_lag1"
[159] "cliente_edad_lag1"
[160] "cliente_antiguedad_lag1"
[161] "mrentabilidad_lag1"
[162] "mrentabilidad_annual_lag1"
[163] "mcomisiones_lag1"
[164] "mactivos_margen_lag1"
[165] "mpasivos_margen_lag1"
[166] "cproductos_lag1"
[167] "tcuentas_lag1"
[168] "ccuenta_corriente_lag1"
[169] "mcuenta_corriente_adicional_lag1"
[170] "mcuenta_corriente_lag1"
[171] "ccaja_ahorro_lag1"
[172] "mcaja_ahorro_lag1"
[173] "mcaja_ahorro_adicional_lag1"
[174] "mcaja_ahorro_dolares_lag1"
[175] "cdescubierto_preacordado_lag1"
[176] "mcuentas_saldo_lag1"
[177] "ctarjeta_debito_lag1"
[178] "ctarjeta_debito_transacciones_lag1"
[179] "mautoservicio_lag1"
[180] "ctarjeta_visa_lag1"
[181] "ctarjeta_visa_transacciones_lag1"
[182] "mtarjeta_visa_consumo_lag1"
[183] "ctarjeta_master_lag1"
[184] "ctarjeta_master_transacciones_lag1"
[185] "mtarjeta_master_consumo_lag1"
[186] "cprestamos_personales_lag1"
[187] "mprestamos_personales_lag1"
[188] "cprestamos_prendarios_lag1"
[189] "mprestamos_prendarios_lag1"
[190] "cprestamos_hipotecarios_lag1"
[191] "mprestamos_hipotecarios_lag1"
[192] "cplazo_fijo_lag1"
[193] "mplazo_fijo_dolares_lag1"
[194] "mplazo_fijo_pesos_lag1"
[195] "cinversion1_lag1"
[196] "minversion1_pesos_lag1"
[197] "minversion1_dolares_lag1"
[198] "cinversion2_lag1"
[199] "minversion2_lag1"
[200] "cseguro_vida_lag1"
[201] "cseguro_auto_lag1"
[202] "cseguro_vivienda_lag1"
[203] "cseguro_accidentes_personales_lag1"
[204] "ccaja_seguridad_lag1"
[205] "cpayroll_trx_lag1"
[206] "mpayroll_lag1"
[207] "mpayroll2_lag1"
[208] "cpayroll2_trx_lag1"
[209] "ccuenta_debitos_automaticos_lag1"
[210] "mcuenta_debitos_automaticos_lag1"
[211] "ctarjeta_visa_debitos_automaticos_lag1"
[212] "mttarjeta_visa_debitos_automaticos_lag1"
[213] "ctarjeta_master_debitos_automaticos_lag1"
[214] "mttarjeta_master_debitos_automaticos_lag1"
[215] "cpagodeservicios_lag1"
[216] "mpagodeservicios_lag1"
[217] "cpagomiscuentas_lag1"
[218] "mpagomiscuentas_lag1"
[219] "ccajeros_propios_descuentos_lag1"
[220] "mcajeros_propios_descuentos_lag1"
[221] "ctarjeta_visa_descuentos_lag1"
[222] "mtarjeta_visa_descuentos_lag1"
[223] "ctarjeta_master_descuentos_lag1"
[224] "mtarjeta_master_descuentos_lag1"
[225] "ccomisiones_mantenimiento_lag1"
[226] "mcomisiones_mantenimiento_lag1"
[227] "ccomisiones_otras_lag1"
[228] "mcomisiones_otras_lag1"
[229] "cforex_lag1"
[230] "cforex_buy_lag1"
[231] "mforex_buy_lag1"
[232] "cforex_sell_lag1"
[233] "mforex_sell_lag1"
[234] "ctransferencias_recibidas_lag1"
[235] "mtransferencias_recibidas_lag1"
[236] "ctransferencias_emitidas_lag1"
[237] "mtransferencias_emitidas_lag1"
[238] "cextraccion_autoservicio_lag1"
[239] "mextraccion_autoservicio_lag1"
[240] "ccheques_depositados_lag1"
[241] "mcheques_depositados_lag1"
[242] "ccheques_emitidos_lag1"
[243] "mcheques_emitidos_lag1"
[244] "ccheques_depositados_rechazados_lag1"
[245] "mcheques_depositados_rechazados_lag1"
[246] "ccheques_emitidos_rechazados_lag1"
[247] "mcheques_emitidos_rechazados_lag1"
[248] "tcallcenter_lag1"
[249] "ccallcenter_transacciones_lag1"
[250] "thomebanking_lag1"
[251] "chomebanking_transacciones_lag1"
[252] "ccajas_transacciones_lag1"
[253] "ccajas_consultas_lag1"
[254] "ccajas_depositos_lag1"
[255] "ccajas_extracciones_lag1"
[256] "ccajas_otras_lag1"
[257] "catm_trx_lag1"
[258] "matm_lag1"
[259] "catm_trx_other_lag1"
[260] "matm_other_lag1"
[261] "ctrx_quarter_lag1"
[262] "tmobile_app_lag1"
[263] "cmobile_app_trx_lag1"
[264] "Master_delinquency_lag1"
[265] "Master_status_lag1"
[266] "Master_mfinanciacion_limite_lag1"
[267] "Master_Fvencimiento_lag1"
[268] "Master_Finiciomora_lag1"
[269] "Master_msaldototal_lag1"
[270] "Master_msaldopesos_lag1"
[271] "Master_msaldodolares_lag1"
[272] "Master_mconsumospesos_lag1"
[273] "Master_mconsumosdolares_lag1"
[274] "Master_mlimitecompra_lag1"
[275] "Master_madelantopesos_lag1"
[276] "Master_madelantodolares_lag1"
[277] "Master_fultimo_cierre_lag1"
[278] "Master_mpagado_lag1"
[279] "Master_mpagospesos_lag1"
[280] "Master_mpagosdolares_lag1"
[281] "Master_fechaalta_lag1"
[282] "Master_mconsumototal_lag1"
[283] "Master_cconsumos_lag1"
[284] "Master_cadelantosefectivo_lag1"
[285] "Master_mpagominimo_lag1"
[286] "Visa_delinquency_lag1"
[287] "Visa_status_lag1"
[288] "Visa_mfinanciacion_limite_lag1"
[289] "Visa_Fvencimiento_lag1"
[290] "Visa_Finiciomora_lag1"
[291] "Visa_msaldototal_lag1"
[292] "Visa_msaldopesos_lag1"
[293] "Visa_msaldodolares_lag1"
[294] "Visa_mconsumospesos_lag1"
[295] "Visa_mconsumosdolares_lag1"
[296] "Visa_mlimitecompra_lag1"
[297] "Visa_madelantopesos_lag1"
[298] "Visa_madelantodolares_lag1"
[299] "Visa_fultimo_cierre_lag1"
[300] "Visa_mpagado_lag1"
[301] "Visa_mpagospesos_lag1"
[302] "Visa_mpagosdolares_lag1"
[303] "Visa_fechaalta_lag1"
[304] "Visa_mconsumototal_lag1"
[305] "Visa_cconsumos_lag1"
[306] "Visa_cadelantosefectivo_lag1"
[307] "Visa_mpagominimo_lag1"
[308] "active_quarter_lag2"
[309] "cliente_vip_lag2"
[310] "internet_lag2"
[311] "cliente_edad_lag2"
[312] "cliente_antiguedad_lag2"
[313] "mrentabilidad_lag2"
[314] "mrentabilidad_annual_lag2"
[315] "mcomisiones_lag2"
[316] "mactivos_margen_lag2"
[317] "mpasivos_margen_lag2"
[318] "cproductos_lag2"
[319] "tcuentas_lag2"
[320] "ccuenta_corriente_lag2"
[321] "mcuenta_corriente_adicional_lag2"
[322] "mcuenta_corriente_lag2"
[323] "ccaja_ahorro_lag2"
[324] "mcaja_ahorro_lag2"
[325] "mcaja_ahorro_adicional_lag2"
[326] "mcaja_ahorro_dolares_lag2"
[327] "cdescubierto_preacordado_lag2"
[328] "mcuentas_saldo_lag2"
[329] "ctarjeta_debito_lag2"
[330] "ctarjeta_debito_transacciones_lag2"
[331] "mautoservicio_lag2"
[332] "ctarjeta_visa_lag2"
[333] "ctarjeta_visa_transacciones_lag2"
[334] "mtarjeta_visa_consumo_lag2"
[335] "ctarjeta_master_lag2"
[336] "ctarjeta_master_transacciones_lag2"
[337] "mtarjeta_master_consumo_lag2"
[338] "cprestamos_personales_lag2"
[339] "mprestamos_personales_lag2"
[340] "cprestamos_prendarios_lag2"
[341] "mprestamos_prendarios_lag2"
[342] "cprestamos_hipotecarios_lag2"
[343] "mprestamos_hipotecarios_lag2"
[344] "cplazo_fijo_lag2"
[345] "mplazo_fijo_dolares_lag2"
[346] "mplazo_fijo_pesos_lag2"
[347] "cinversion1_lag2"
[348] "minversion1_pesos_lag2"
[349] "minversion1_dolares_lag2"
[350] "cinversion2_lag2"
[351] "minversion2_lag2"
[352] "cseguro_vida_lag2"
[353] "cseguro_auto_lag2"
[354] "cseguro_vivienda_lag2"
[355] "cseguro_accidentes_personales_lag2"
[356] "ccaja_seguridad_lag2"
[357] "cpayroll_trx_lag2"
[358] "mpayroll_lag2"
[359] "mpayroll2_lag2"
[360] "cpayroll2_trx_lag2"
[361] "ccuenta_debitos_automaticos_lag2"
[362] "mcuenta_debitos_automaticos_lag2"
[363] "ctarjeta_visa_debitos_automaticos_lag2"
[364] "mttarjeta_visa_debitos_automaticos_lag2"
[365] "ctarjeta_master_debitos_automaticos_lag2"
[366] "mttarjeta_master_debitos_automaticos_lag2"
[367] "cpagodeservicios_lag2"
[368] "mpagodeservicios_lag2"
[369] "cpagomiscuentas_lag2"
[370] "mpagomiscuentas_lag2"
[371] "ccajeros_propios_descuentos_lag2"
[372] "mcajeros_propios_descuentos_lag2"
[373] "ctarjeta_visa_descuentos_lag2"
[374] "mtarjeta_visa_descuentos_lag2"
[375] "ctarjeta_master_descuentos_lag2"
[376] "mtarjeta_master_descuentos_lag2"
[377] "ccomisiones_mantenimiento_lag2"
[378] "mcomisiones_mantenimiento_lag2"
[379] "ccomisiones_otras_lag2"
[380] "mcomisiones_otras_lag2"
[381] "cforex_lag2"
[382] "cforex_buy_lag2"
[383] "mforex_buy_lag2"
[384] "cforex_sell_lag2"
[385] "mforex_sell_lag2"
[386] "ctransferencias_recibidas_lag2"
[387] "mtransferencias_recibidas_lag2"
[388] "ctransferencias_emitidas_lag2"
[389] "mtransferencias_emitidas_lag2"
[390] "cextraccion_autoservicio_lag2"
[391] "mextraccion_autoservicio_lag2"
[392] "ccheques_depositados_lag2"
[393] "mcheques_depositados_lag2"
[394] "ccheques_emitidos_lag2"
[395] "mcheques_emitidos_lag2"
[396] "ccheques_depositados_rechazados_lag2"
[397] "mcheques_depositados_rechazados_lag2"
[398] "ccheques_emitidos_rechazados_lag2"
[399] "mcheques_emitidos_rechazados_lag2"
[400] "tcallcenter_lag2"
[401] "ccallcenter_transacciones_lag2"
[402] "thomebanking_lag2"
[403] "chomebanking_transacciones_lag2"
[404] "ccajas_transacciones_lag2"
[405] "ccajas_consultas_lag2"
[406] "ccajas_depositos_lag2"
[407] "ccajas_extracciones_lag2"
[408] "ccajas_otras_lag2"
[409] "catm_trx_lag2"
[410] "matm_lag2"
[411] "catm_trx_other_lag2"
[412] "matm_other_lag2"
[413] "ctrx_quarter_lag2"
[414] "tmobile_app_lag2"
[415] "cmobile_app_trx_lag2"
[416] "Master_delinquency_lag2"
[417] "Master_status_lag2"
[418] "Master_mfinanciacion_limite_lag2"
[419] "Master_Fvencimiento_lag2"
[420] "Master_Finiciomora_lag2"
[421] "Master_msaldototal_lag2"
[422] "Master_msaldopesos_lag2"
[423] "Master_msaldodolares_lag2"
[424] "Master_mconsumospesos_lag2"
[425] "Master_mconsumosdolares_lag2"
[426] "Master_mlimitecompra_lag2"
[427] "Master_madelantopesos_lag2"
[428] "Master_madelantodolares_lag2"
[429] "Master_fultimo_cierre_lag2"
[430] "Master_mpagado_lag2"
[431] "Master_mpagospesos_lag2"
[432] "Master_mpagosdolares_lag2"
[433] "Master_fechaalta_lag2"
[434] "Master_mconsumototal_lag2"
[435] "Master_cconsumos_lag2"
[436] "Master_cadelantosefectivo_lag2"
[437] "Master_mpagominimo_lag2"
[438] "Visa_delinquency_lag2"
[439] "Visa_status_lag2"
[440] "Visa_mfinanciacion_limite_lag2"
[441] "Visa_Fvencimiento_lag2"
[442] "Visa_Finiciomora_lag2"
[443] "Visa_msaldototal_lag2"
[444] "Visa_msaldopesos_lag2"
[445] "Visa_msaldodolares_lag2"
[446] "Visa_mconsumospesos_lag2"
[447] "Visa_mconsumosdolares_lag2"
[448] "Visa_mlimitecompra_lag2"
[449] "Visa_madelantopesos_lag2"
[450] "Visa_madelantodolares_lag2"
[451] "Visa_fultimo_cierre_lag2"
[452] "Visa_mpagado_lag2"
[453] "Visa_mpagospesos_lag2"
[454] "Visa_mpagosdolares_lag2"
[455] "Visa_fechaalta_lag2"
[456] "Visa_mconsumototal_lag2"
[457] "Visa_cconsumos_lag2"
[458] "Visa_cadelantosefectivo_lag2"
[459] "Visa_mpagominimo_lag2"
[460] "active_quarter_delta1"
[461] "active_quarter_delta2"
[462] "cliente_vip_delta1"
[463] "cliente_vip_delta2"
[464] "internet_delta1"
[465] "internet_delta2"
[466] "cliente_edad_delta1"
[467] "cliente_edad_delta2"
[468] "cliente_antiguedad_delta1"
[469] "cliente_antiguedad_delta2"
[470] "mrentabilidad_delta1"
[471] "mrentabilidad_delta2"
[472] "mrentabilidad_annual_delta1"
[473] "mrentabilidad_annual_delta2"
[474] "mcomisiones_delta1"
[475] "mcomisiones_delta2"
[476] "mactivos_margen_delta1"
[477] "mactivos_margen_delta2"
[478] "mpasivos_margen_delta1"
[479] "mpasivos_margen_delta2"
[480] "cproductos_delta1"
[481] "cproductos_delta2"
[482] "tcuentas_delta1"
[483] "tcuentas_delta2"
[484] "ccuenta_corriente_delta1"
[485] "ccuenta_corriente_delta2"
[486] "mcuenta_corriente_adicional_delta1"
[487] "mcuenta_corriente_adicional_delta2"
[488] "mcuenta_corriente_delta1"
[489] "mcuenta_corriente_delta2"
[490] "ccaja_ahorro_delta1"
[491] "ccaja_ahorro_delta2"
[492] "mcaja_ahorro_delta1"
[493] "mcaja_ahorro_delta2"
[494] "mcaja_ahorro_adicional_delta1"
[495] "mcaja_ahorro_adicional_delta2"
[496] "mcaja_ahorro_dolares_delta1"
[497] "mcaja_ahorro_dolares_delta2"
[498] "cdescubierto_preacordado_delta1"
[499] "cdescubierto_preacordado_delta2"
[500] "mcuentas_saldo_delta1"
[501] "mcuentas_saldo_delta2"
[502] "ctarjeta_debito_delta1"
[503] "ctarjeta_debito_delta2"
[504] "ctarjeta_debito_transacciones_delta1"
[505] "ctarjeta_debito_transacciones_delta2"
[506] "mautoservicio_delta1"
[507] "mautoservicio_delta2"
[508] "ctarjeta_visa_delta1"
[509] "ctarjeta_visa_delta2"
[510] "ctarjeta_visa_transacciones_delta1"
[511] "ctarjeta_visa_transacciones_delta2"
[512] "mtarjeta_visa_consumo_delta1"
[513] "mtarjeta_visa_consumo_delta2"
[514] "ctarjeta_master_delta1"
[515] "ctarjeta_master_delta2"
[516] "ctarjeta_master_transacciones_delta1"
[517] "ctarjeta_master_transacciones_delta2"
[518] "mtarjeta_master_consumo_delta1"
[519] "mtarjeta_master_consumo_delta2"
[520] "cprestamos_personales_delta1"
[521] "cprestamos_personales_delta2"
[522] "mprestamos_personales_delta1"
[523] "mprestamos_personales_delta2"
[524] "cprestamos_prendarios_delta1"
[525] "cprestamos_prendarios_delta2"
[526] "mprestamos_prendarios_delta1"
[527] "mprestamos_prendarios_delta2"
[528] "cprestamos_hipotecarios_delta1"
[529] "cprestamos_hipotecarios_delta2"
[530] "mprestamos_hipotecarios_delta1"
[531] "mprestamos_hipotecarios_delta2"
[532] "cplazo_fijo_delta1"
[533] "cplazo_fijo_delta2"
[534] "mplazo_fijo_dolares_delta1"
[535] "mplazo_fijo_dolares_delta2"
[536] "mplazo_fijo_pesos_delta1"
[537] "mplazo_fijo_pesos_delta2"
[538] "cinversion1_delta1"
[539] "cinversion1_delta2"
[540] "minversion1_pesos_delta1"
[541] "minversion1_pesos_delta2"
[542] "minversion1_dolares_delta1"
[543] "minversion1_dolares_delta2"
[544] "cinversion2_delta1"
[545] "cinversion2_delta2"
[546] "minversion2_delta1"
[547] "minversion2_delta2"
[548] "cseguro_vida_delta1"
[549] "cseguro_vida_delta2"
[550] "cseguro_auto_delta1"
[551] "cseguro_auto_delta2"
[552] "cseguro_vivienda_delta1"
[553] "cseguro_vivienda_delta2"
[554] "cseguro_accidentes_personales_delta1"
[555] "cseguro_accidentes_personales_delta2"
[556] "ccaja_seguridad_delta1"
[557] "ccaja_seguridad_delta2"
[558] "cpayroll_trx_delta1"
[559] "cpayroll_trx_delta2"
[560] "mpayroll_delta1"
[561] "mpayroll_delta2"
[562] "mpayroll2_delta1"
[563] "mpayroll2_delta2"
[564] "cpayroll2_trx_delta1"
[565] "cpayroll2_trx_delta2"
[566] "ccuenta_debitos_automaticos_delta1"
[567] "ccuenta_debitos_automaticos_delta2"
[568] "mcuenta_debitos_automaticos_delta1"
[569] "mcuenta_debitos_automaticos_delta2"
[570] "ctarjeta_visa_debitos_automaticos_delta1"
[571] "ctarjeta_visa_debitos_automaticos_delta2"
[572] "mttarjeta_visa_debitos_automaticos_delta1"
[573] "mttarjeta_visa_debitos_automaticos_delta2"
[574] "ctarjeta_master_debitos_automaticos_delta1"
[575] "ctarjeta_master_debitos_automaticos_delta2"
[576] "mttarjeta_master_debitos_automaticos_delta1"
[577] "mttarjeta_master_debitos_automaticos_delta2"
[578] "cpagodeservicios_delta1"
[579] "cpagodeservicios_delta2"
[580] "mpagodeservicios_delta1"
[581] "mpagodeservicios_delta2"
[582] "cpagomiscuentas_delta1"
[583] "cpagomiscuentas_delta2"
[584] "mpagomiscuentas_delta1"
[585] "mpagomiscuentas_delta2"
[586] "ccajeros_propios_descuentos_delta1"
[587] "ccajeros_propios_descuentos_delta2"
[588] "mcajeros_propios_descuentos_delta1"
[589] "mcajeros_propios_descuentos_delta2"
[590] "ctarjeta_visa_descuentos_delta1"
[591] "ctarjeta_visa_descuentos_delta2"
[592] "mtarjeta_visa_descuentos_delta1"
[593] "mtarjeta_visa_descuentos_delta2"
[594] "ctarjeta_master_descuentos_delta1"
[595] "ctarjeta_master_descuentos_delta2"
[596] "mtarjeta_master_descuentos_delta1"
[597] "mtarjeta_master_descuentos_delta2"
[598] "ccomisiones_mantenimiento_delta1"
[599] "ccomisiones_mantenimiento_delta2"
[600] "mcomisiones_mantenimiento_delta1"
[601] "mcomisiones_mantenimiento_delta2"
[602] "ccomisiones_otras_delta1"
[603] "ccomisiones_otras_delta2"
[604] "mcomisiones_otras_delta1"
[605] "mcomisiones_otras_delta2"
[606] "cforex_delta1"
[607] "cforex_delta2"
[608] "cforex_buy_delta1"
[609] "cforex_buy_delta2"
[610] "mforex_buy_delta1"
[611] "mforex_buy_delta2"
[612] "cforex_sell_delta1"
[613] "cforex_sell_delta2"
[614] "mforex_sell_delta1"
[615] "mforex_sell_delta2"
[616] "ctransferencias_recibidas_delta1"
[617] "ctransferencias_recibidas_delta2"
[618] "mtransferencias_recibidas_delta1"
[619] "mtransferencias_recibidas_delta2"
[620] "ctransferencias_emitidas_delta1"
[621] "ctransferencias_emitidas_delta2"
[622] "mtransferencias_emitidas_delta1"
[623] "mtransferencias_emitidas_delta2"
[624] "cextraccion_autoservicio_delta1"
[625] "cextraccion_autoservicio_delta2"
[626] "mextraccion_autoservicio_delta1"
[627] "mextraccion_autoservicio_delta2"
[628] "ccheques_depositados_delta1"
[629] "ccheques_depositados_delta2"
[630] "mcheques_depositados_delta1"

In [16]:
if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

Loading required package: lightgbm

In [17]:
ncol(dataset)
colnames(dataset)

[1] 915

  [1] "numero_de_cliente"
  [2] "foto_mes"
  [3] "active_quarter"
  [4] "cliente_vip"
  [5] "internet"
  [6] "cliente_edad"
  [7] "cliente_antiguedad"
  [8] "mrentabilidad"
  [9] "mrentabilidad_annual"
 [10] "mcomisiones"
 [11] "mactivos_margen"
 [12] "mpasivos_margen"
 [13] "cproductos"
 [14] "tcuentas"
 [15] "ccuenta_corriente"
 [16] "mcuenta_corriente_adicional"
 [17] "mcuenta_corriente"
 [18] "ccaja_ahorro"
 [19] "mcaja_ahorro"
 [20] "mcaja_ahorro_adicional"
 [21] "mcaja_ahorro_dolares"
 [22] "cdescubierto_preacordado"
 [23] "mcuentas_saldo"
 [24] "ctarjeta_debito"
 [25] "ctarjeta_debito_transacciones"
 [26] "mautoservicio"
 [27] "ctarjeta_visa"
 [28] "ctarjeta_visa_transacciones"
 [29] "mtarjeta_visa_consumo"
 [30] "ctarjeta_master"
 [31] "ctarjeta_master_transacciones"
 [32] "mtarjeta_master_consumo"
 [33] "cprestamos_personales"
 [34] "mprestamos_personales"
 [35] "cprestamos_prendarios"
 [36] "mprestamos_prendarios"
 [37] "cprestamos_hipotecarios"
 [38] "mprestamos_hipotecarios"
 [39] "cplazo_fijo"
 [40] "mplazo_fijo_dolares"
 [41] "mplazo_fijo_pesos"
 [42] "cinversion1"
 [43] "minversion1_pesos"
 [44] "minversion1_dolares"
 [45] "cinversion2"
 [46] "minversion2"
 [47] "cseguro_vida"
 [48] "cseguro_auto"
 [49] "cseguro_vivienda"
 [50] "cseguro_accidentes_personales"
 [51] "ccaja_seguridad"
 [52] "cpayroll_trx"
 [53] "mpayroll"
 [54] "mpayroll2"
 [55] "cpayroll2_trx"
 [56] "ccuenta_debitos_automaticos"
 [57] "mcuenta_debitos_automaticos"
 [58] "ctarjeta_visa_debitos_automaticos"
 [59] "mttarjeta_visa_debitos_automaticos"
 [60] "ctarjeta_master_debitos_automaticos"
 [61] "mttarjeta_master_debitos_automaticos"
 [62] "cpagodeservicios"
 [63] "mpagodeservicios"
 [64] "cpagomiscuentas"
 [65] "mpagomiscuentas"
 [66] "ccajeros_propios_descuentos"
 [67] "mcajeros_propios_descuentos"
 [68] "ctarjeta_visa_descuentos"
 [69] "mtarjeta_visa_descuentos"
 [70] "ctarjeta_master_descuentos"
 [71] "mtarjeta_master_descuentos"
 [72] "ccomisiones_mantenimiento"
 [73] "mcomisiones_mantenimiento"
 [74] "ccomisiones_otras"
 [75] "mcomisiones_otras"
 [76] "cforex"
 [77] "cforex_buy"
 [78] "mforex_buy"
 [79] "cforex_sell"
 [80] "mforex_sell"
 [81] "ctransferencias_recibidas"
 [82] "mtransferencias_recibidas"
 [83] "ctransferencias_emitidas"
 [84] "mtransferencias_emitidas"
 [85] "cextraccion_autoservicio"
 [86] "mextraccion_autoservicio"
 [87] "ccheques_depositados"
 [88] "mcheques_depositados"
 [89] "ccheques_emitidos"
 [90] "mcheques_emitidos"
 [91] "ccheques_depositados_rechazados"
 [92] "mcheques_depositados_rechazados"
 [93] "ccheques_emitidos_rechazados"
 [94] "mcheques_emitidos_rechazados"
 [95] "tcallcenter"
 [96] "ccallcenter_transacciones"
 [97] "thomebanking"
 [98] "chomebanking_transacciones"
 [99] "ccajas_transacciones"
[100] "ccajas_consultas"
[101] "ccajas_depositos"
[102] "ccajas_extracciones"
[103] "ccajas_otras"
[104] "catm_trx"
[105] "matm"
[106] "catm_trx_other"
[107] "matm_other"
[108] "ctrx_quarter"
[109] "tmobile_app"
[110] "cmobile_app_trx"
[111] "Master_delinquency"
[112] "Master_status"
[113] "Master_mfinanciacion_limite"
[114] "Master_Fvencimiento"
[115] "Master_Finiciomora"
[116] "Master_msaldototal"
[117] "Master_msaldopesos"
[118] "Master_msaldodolares"
[119] "Master_mconsumospesos"
[120] "Master_mconsumosdolares"
[121] "Master_mlimitecompra"
[122] "Master_madelantopesos"
[123] "Master_madelantodolares"
[124] "Master_fultimo_cierre"
[125] "Master_mpagado"
[126] "Master_mpagospesos"
[127] "Master_mpagosdolares"
[128] "Master_fechaalta"
[129] "Master_mconsumototal"
[130] "Master_cconsumos"
[131] "Master_cadelantosefectivo"
[132] "Master_mpagominimo"
[133] "Visa_delinquency"
[134] "Visa_status"
[135] "Visa_mfinanciacion_limite"
[136] "Visa_Fvencimiento"
[137] "Visa_Finiciomora"
[138] "Visa_msaldototal"
[139] "Visa_msaldopesos"
[140] "Visa_msaldodolares"
[141] "Visa_mconsumospesos"
[142] "Visa_mconsumosdolares"
[143] "Visa_mlimitecompra"
[144] "Visa_madelantopesos"
[145] "Visa_madelantodolares"
[146] "Visa_fultimo_cierre"
[147] "Visa_mpagado"
[148] "Visa_mpagospesos"
[149] "Visa_mpagosdolares"
[150] "Visa_fechaalta"
[151] "Visa_mconsumototal"
[152] "Visa_cconsumos"
[153] "Visa_cadelantosefectivo"
[154] "Visa_mpagominimo"
[155] "clase_ternaria"
[156] "active_quarter_lag1"
[157] "cliente_vip_lag1"
[158] "internet_lag1"
[159] "cliente_edad_lag1"
[160] "cliente_antiguedad_lag1"
[161] "mrentabilidad_lag1"
[162] "mrentabilidad_annual_lag1"
[163] "mcomisiones_lag1"
[164] "mactivos_margen_lag1"
[165] "mpasivos_margen_lag1"
[166] "cproductos_lag1"
[167] "tcuentas_lag1"
[168] "ccuenta_corriente_lag1"
[169] "mcuenta_corriente_adicional_lag1"
[170] "mcuenta_corriente_lag1"
[171] "ccaja_ahorro_lag1"
[172] "mcaja_ahorro_lag1"
[173] "mcaja_ahorro_adicional_lag1"
[174] "mcaja_ahorro_dolares_lag1"
[175] "cdescubierto_preacordado_lag1"
[176] "mcuentas_saldo_lag1"
[177] "ctarjeta_debito_lag1"
[178] "ctarjeta_debito_transacciones_lag1"
[179] "mautoservicio_lag1"
[180] "ctarjeta_visa_lag1"
[181] "ctarjeta_visa_transacciones_lag1"
[182] "mtarjeta_visa_consumo_lag1"
[183] "ctarjeta_master_lag1"
[184] "ctarjeta_master_transacciones_lag1"
[185] "mtarjeta_master_consumo_lag1"
[186] "cprestamos_personales_lag1"
[187] "mprestamos_personales_lag1"
[188] "cprestamos_prendarios_lag1"
[189] "mprestamos_prendarios_lag1"
[190] "cprestamos_hipotecarios_lag1"
[191] "mprestamos_hipotecarios_lag1"
[192] "cplazo_fijo_lag1"
[193] "mplazo_fijo_dolares_lag1"
[194] "mplazo_fijo_pesos_lag1"
[195] "cinversion1_lag1"
[196] "minversion1_pesos_lag1"
[197] "minversion1_dolares_lag1"
[198] "cinversion2_lag1"
[199] "minversion2_lag1"
[200] "cseguro_vida_lag1"
[201] "cseguro_auto_lag1"
[202] "cseguro_vivienda_lag1"
[203] "cseguro_accidentes_personales_lag1"
[204] "ccaja_seguridad_lag1"
[205] "cpayroll_trx_lag1"
[206] "mpayroll_lag1"
[207] "mpayroll2_lag1"
[208] "cpayroll2_trx_lag1"
[209] "ccuenta_debitos_automaticos_lag1"
[210] "mcuenta_debitos_automaticos_lag1"
[211] "ctarjeta_visa_debitos_automaticos_lag1"
[212] "mttarjeta_visa_debitos_automaticos_lag1"
[213] "ctarjeta_master_debitos_automaticos_lag1"
[214] "mttarjeta_master_debitos_automaticos_lag1"
[215] "cpagodeservicios_lag1"
[216] "mpagodeservicios_lag1"
[217] "cpagomiscuentas_lag1"
[218] "mpagomiscuentas_lag1"
[219] "ccajeros_propios_descuentos_lag1"
[220] "mcajeros_propios_descuentos_lag1"
[221] "ctarjeta_visa_descuentos_lag1"
[222] "mtarjeta_visa_descuentos_lag1"
[223] "ctarjeta_master_descuentos_lag1"
[224] "mtarjeta_master_descuentos_lag1"
[225] "ccomisiones_mantenimiento_lag1"
[226] "mcomisiones_mantenimiento_lag1"
[227] "ccomisiones_otras_lag1"
[228] "mcomisiones_otras_lag1"
[229] "cforex_lag1"
[230] "cforex_buy_lag1"
[231] "mforex_buy_lag1"
[232] "cforex_sell_lag1"
[233] "mforex_sell_lag1"
[234] "ctransferencias_recibidas_lag1"
[235] "mtransferencias_recibidas_lag1"
[236] "ctransferencias_emitidas_lag1"
[237] "mtransferencias_emitidas_lag1"
[238] "cextraccion_autoservicio_lag1"
[239] "mextraccion_autoservicio_lag1"
[240] "ccheques_depositados_lag1"
[241] "mcheques_depositados_lag1"
[242] "ccheques_emitidos_lag1"
[243] "mcheques_emitidos_lag1"
[244] "ccheques_depositados_rechazados_lag1"
[245] "mcheques_depositados_rechazados_lag1"
[246] "ccheques_emitidos_rechazados_lag1"
[247] "mcheques_emitidos_rechazados_lag1"
[248] "tcallcenter_lag1"
[249] "ccallcenter_transacciones_lag1"
[250] "thomebanking_lag1"
[251] "chomebanking_transacciones_lag1"
[252] "ccajas_transacciones_lag1"
[253] "ccajas_consultas_lag1"
[254] "ccajas_depositos_lag1"
[255] "ccajas_extracciones_lag1"
[256] "ccajas_otras_lag1"
[257] "catm_trx_lag1"
[258] "matm_lag1"
[259] "catm_trx_other_lag1"
[260] "matm_other_lag1"
[261] "ctrx_quarter_lag1"
[262] "tmobile_app_lag1"
[263] "cmobile_app_trx_lag1"
[264] "Master_delinquency_lag1"
[265] "Master_status_lag1"
[266] "Master_mfinanciacion_limite_lag1"
[267] "Master_Fvencimiento_lag1"
[268] "Master_Finiciomora_lag1"
[269] "Master_msaldototal_lag1"
[270] "Master_msaldopesos_lag1"
[271] "Master_msaldodolares_lag1"
[272] "Master_mconsumospesos_lag1"
[273] "Master_mconsumosdolares_lag1"
[274] "Master_mlimitecompra_lag1"
[275] "Master_madelantopesos_lag1"
[276] "Master_madelantodolares_lag1"
[277] "Master_fultimo_cierre_lag1"
[278] "Master_mpagado_lag1"
[279] "Master_mpagospesos_lag1"
[280] "Master_mpagosdolares_lag1"
[281] "Master_fechaalta_lag1"
[282] "Master_mconsumototal_lag1"
[283] "Master_cconsumos_lag1"
[284] "Master_cadelantosefectivo_lag1"
[285] "Master_mpagominimo_lag1"
[286] "Visa_delinquency_lag1"
[287] "Visa_status_lag1"
[288] "Visa_mfinanciacion_limite_lag1"
[289] "Visa_Fvencimiento_lag1"
[290] "Visa_Finiciomora_lag1"
[291] "Visa_msaldototal_lag1"
[292] "Visa_msaldopesos_lag1"
[293] "Visa_msaldodolares_lag1"
[294] "Visa_mconsumospesos_lag1"
[295] "Visa_mconsumosdolares_lag1"
[296] "Visa_mlimitecompra_lag1"
[297] "Visa_madelantopesos_lag1"
[298] "Visa_madelantodolares_lag1"
[299] "Visa_fultimo_cierre_lag1"
[300] "Visa_mpagado_lag1"
[301] "Visa_mpagospesos_lag1"
[302] "Visa_mpagosdolares_lag1"
[303] "Visa_fechaalta_lag1"
[304] "Visa_mconsumototal_lag1"
[305] "Visa_cconsumos_lag1"
[306] "Visa_cadelantosefectivo_lag1"
[307] "Visa_mpagominimo_lag1"
[308] "active_quarter_lag2"
[309] "cliente_vip_lag2"
[310] "internet_lag2"
[311] "cliente_edad_lag2"
[312] "cliente_antiguedad_lag2"
[313] "mrentabilidad_lag2"
[314] "mrentabilidad_annual_lag2"
[315] "mcomisiones_lag2"
[316] "mactivos_margen_lag2"
[317] "mpasivos_margen_lag2"
[318] "cproductos_lag2"
[319] "tcuentas_lag2"
[320] "ccuenta_corriente_lag2"
[321] "mcuenta_corriente_adicional_lag2"
[322] "mcuenta_corriente_lag2"
[323] "ccaja_ahorro_lag2"
[324] "mcaja_ahorro_lag2"
[325] "mcaja_ahorro_adicional_lag2"
[326] "mcaja_ahorro_dolares_lag2"
[327] "cdescubierto_preacordado_lag2"
[328] "mcuentas_saldo_lag2"
[329] "ctarjeta_debito_lag2"
[330] "ctarjeta_debito_transacciones_lag2"
[331] "mautoservicio_lag2"
[332] "ctarjeta_visa_lag2"
[333] "ctarjeta_visa_transacciones_lag2"
[334] "mtarjeta_visa_consumo_lag2"
[335] "ctarjeta_master_lag2"
[336] "ctarjeta_master_transacciones_lag2"
[337] "mtarjeta_master_consumo_lag2"
[338] "cprestamos_personales_lag2"
[339] "mprestamos_personales_lag2"
[340] "cprestamos_prendarios_lag2"
[341] "mprestamos_prendarios_lag2"
[342] "cprestamos_hipotecarios_lag2"
[343] "mprestamos_hipotecarios_lag2"
[344] "cplazo_fijo_lag2"
[345] "mplazo_fijo_dolares_lag2"
[346] "mplazo_fijo_pesos_lag2"
[347] "cinversion1_lag2"
[348] "minversion1_pesos_lag2"
[349] "minversion1_dolares_lag2"
[350] "cinversion2_lag2"
[351] "minversion2_lag2"
[352] "cseguro_vida_lag2"
[353] "cseguro_auto_lag2"
[354] "cseguro_vivienda_lag2"
[355] "cseguro_accidentes_personales_lag2"
[356] "ccaja_seguridad_lag2"
[357] "cpayroll_trx_lag2"
[358] "mpayroll_lag2"
[359] "mpayroll2_lag2"
[360] "cpayroll2_trx_lag2"
[361] "ccuenta_debitos_automaticos_lag2"
[362] "mcuenta_debitos_automaticos_lag2"
[363] "ctarjeta_visa_debitos_automaticos_lag2"
[364] "mttarjeta_visa_debitos_automaticos_lag2"
[365] "ctarjeta_master_debitos_automaticos_lag2"
[366] "mttarjeta_master_debitos_automaticos_lag2"
[367] "cpagodeservicios_lag2"
[368] "mpagodeservicios_lag2"
[369] "cpagomiscuentas_lag2"
[370] "mpagomiscuentas_lag2"
[371] "ccajeros_propios_descuentos_lag2"
[372] "mcajeros_propios_descuentos_lag2"
[373] "ctarjeta_visa_descuentos_lag2"
[374] "mtarjeta_visa_descuentos_lag2"
[375] "ctarjeta_master_descuentos_lag2"
[376] "mtarjeta_master_descuentos_lag2"
[377] "ccomisiones_mantenimiento_lag2"
[378] "mcomisiones_mantenimiento_lag2"
[379] "ccomisiones_otras_lag2"
[380] "mcomisiones_otras_lag2"
[381] "cforex_lag2"
[382] "cforex_buy_lag2"
[383] "mforex_buy_lag2"
[384] "cforex_sell_lag2"
[385] "mforex_sell_lag2"
[386] "ctransferencias_recibidas_lag2"
[387] "mtransferencias_recibidas_lag2"
[388] "ctransferencias_emitidas_lag2"
[389] "mtransferencias_emitidas_lag2"
[390] "cextraccion_autoservicio_lag2"
[391] "mextraccion_autoservicio_lag2"
[392] "ccheques_depositados_lag2"
[393] "mcheques_depositados_lag2"
[394] "ccheques_emitidos_lag2"
[395] "mcheques_emitidos_lag2"
[396] "ccheques_depositados_rechazados_lag2"
[397] "mcheques_depositados_rechazados_lag2"
[398] "ccheques_emitidos_rechazados_lag2"
[399] "mcheques_emitidos_rechazados_lag2"
[400] "tcallcenter_lag2"
[401] "ccallcenter_transacciones_lag2"
[402] "thomebanking_lag2"
[403] "chomebanking_transacciones_lag2"
[404] "ccajas_transacciones_lag2"
[405] "ccajas_consultas_lag2"
[406] "ccajas_depositos_lag2"
[407] "ccajas_extracciones_lag2"
[408] "ccajas_otras_lag2"
[409] "catm_trx_lag2"
[410] "matm_lag2"
[411] "catm_trx_other_lag2"
[412] "matm_other_lag2"
[413] "ctrx_quarter_lag2"
[414] "tmobile_app_lag2"
[415] "cmobile_app_trx_lag2"
[416] "Master_delinquency_lag2"
[417] "Master_status_lag2"
[418] "Master_mfinanciacion_limite_lag2"
[419] "Master_Fvencimiento_lag2"
[420] "Master_Finiciomora_lag2"
[421] "Master_msaldototal_lag2"
[422] "Master_msaldopesos_lag2"
[423] "Master_msaldodolares_lag2"
[424] "Master_mconsumospesos_lag2"
[425] "Master_mconsumosdolares_lag2"
[426] "Master_mlimitecompra_lag2"
[427] "Master_madelantopesos_lag2"
[428] "Master_madelantodolares_lag2"
[429] "Master_fultimo_cierre_lag2"
[430] "Master_mpagado_lag2"
[431] "Master_mpagospesos_lag2"
[432] "Master_mpagosdolares_lag2"
[433] "Master_fechaalta_lag2"
[434] "Master_mconsumototal_lag2"
[435] "Master_cconsumos_lag2"
[436] "Master_cadelantosefectivo_lag2"
[437] "Master_mpagominimo_lag2"
[438] "Visa_delinquency_lag2"
[439] "Visa_status_lag2"
[440] "Visa_mfinanciacion_limite_lag2"
[441] "Visa_Fvencimiento_lag2"
[442] "Visa_Finiciomora_lag2"
[443] "Visa_msaldototal_lag2"
[444] "Visa_msaldopesos_lag2"
[445] "Visa_msaldodolares_lag2"
[446] "Visa_mconsumospesos_lag2"
[447] "Visa_mconsumosdolares_lag2"
[448] "Visa_mlimitecompra_lag2"
[449] "Visa_madelantopesos_lag2"
[450] "Visa_madelantodolares_lag2"
[451] "Visa_fultimo_cierre_lag2"
[452] "Visa_mpagado_lag2"
[453] "Visa_mpagospesos_lag2"
[454] "Visa_mpagosdolares_lag2"
[455] "Visa_fechaalta_lag2"
[456] "Visa_mconsumototal_lag2"
[457] "Visa_cconsumos_lag2"
[458] "Visa_cadelantosefectivo_lag2"
[459] "Visa_mpagominimo_lag2"
[460] "active_quarter_delta1"
[461] "active_quarter_delta2"
[462] "cliente_vip_delta1"
[463] "cliente_vip_delta2"
[464] "internet_delta1"
[465] "internet_delta2"
[466] "cliente_edad_delta1"
[467] "cliente_edad_delta2"
[468] "cliente_antiguedad_delta1"
[469] "cliente_antiguedad_delta2"
[470] "mrentabilidad_delta1"
[471] "mrentabilidad_delta2"
[472] "mrentabilidad_annual_delta1"
[473] "mrentabilidad_annual_delta2"
[474] "mcomisiones_delta1"
[475] "mcomisiones_delta2"
[476] "mactivos_margen_delta1"
[477] "mactivos_margen_delta2"
[478] "mpasivos_margen_delta1"
[479] "mpasivos_margen_delta2"
[480] "cproductos_delta1"
[481] "cproductos_delta2"
[482] "tcuentas_delta1"
[483] "tcuentas_delta2"
[484] "ccuenta_corriente_delta1"
[485] "ccuenta_corriente_delta2"
[486] "mcuenta_corriente_adicional_delta1"
[487] "mcuenta_corriente_adicional_delta2"
[488] "mcuenta_corriente_delta1"
[489] "mcuenta_corriente_delta2"
[490] "ccaja_ahorro_delta1"
[491] "ccaja_ahorro_delta2"
[492] "mcaja_ahorro_delta1"
[493] "mcaja_ahorro_delta2"
[494] "mcaja_ahorro_adicional_delta1"
[495] "mcaja_ahorro_adicional_delta2"
[496] "mcaja_ahorro_dolares_delta1"
[497] "mcaja_ahorro_dolares_delta2"
[498] "cdescubierto_preacordado_delta1"
[499] "cdescubierto_preacordado_delta2"
[500] "mcuentas_saldo_delta1"
[501] "mcuentas_saldo_delta2"
[502] "ctarjeta_debito_delta1"
[503] "ctarjeta_debito_delta2"
[504] "ctarjeta_debito_transacciones_delta1"
[505] "ctarjeta_debito_transacciones_delta2"
[506] "mautoservicio_delta1"
[507] "mautoservicio_delta2"
[508] "ctarjeta_visa_delta1"
[509] "ctarjeta_visa_delta2"
[510] "ctarjeta_visa_transacciones_delta1"
[511] "ctarjeta_visa_transacciones_delta2"
[512] "mtarjeta_visa_consumo_delta1"
[513] "mtarjeta_visa_consumo_delta2"
[514] "ctarjeta_master_delta1"
[515] "ctarjeta_master_delta2"
[516] "ctarjeta_master_transacciones_delta1"
[517] "ctarjeta_master_transacciones_delta2"
[518] "mtarjeta_master_consumo_delta1"
[519] "mtarjeta_master_consumo_delta2"
[520] "cprestamos_personales_delta1"
[521] "cprestamos_personales_delta2"
[522] "mprestamos_personales_delta1"
[523] "mprestamos_personales_delta2"
[524] "cprestamos_prendarios_delta1"
[525] "cprestamos_prendarios_delta2"
[526] "mprestamos_prendarios_delta1"
[527] "mprestamos_prendarios_delta2"
[528] "cprestamos_hipotecarios_delta1"
[529] "cprestamos_hipotecarios_delta2"
[530] "mprestamos_hipotecarios_delta1"
[531] "mprestamos_hipotecarios_delta2"
[532] "cplazo_fijo_delta1"
[533] "cplazo_fijo_delta2"
[534] "mplazo_fijo_dolares_delta1"
[535] "mplazo_fijo_dolares_delta2"
[536] "mplazo_fijo_pesos_delta1"
[537] "mplazo_fijo_pesos_delta2"
[538] "cinversion1_delta1"
[539] "cinversion1_delta2"
[540] "minversion1_pesos_delta1"
[541] "minversion1_pesos_delta2"
[542] "minversion1_dolares_delta1"
[543] "minversion1_dolares_delta2"
[544] "cinversion2_delta1"
[545] "cinversion2_delta2"
[546] "minversion2_delta1"
[547] "minversion2_delta2"
[548] "cseguro_vida_delta1"
[549] "cseguro_vida_delta2"
[550] "cseguro_auto_delta1"
[551] "cseguro_auto_delta2"
[552] "cseguro_vivienda_delta1"
[553] "cseguro_vivienda_delta2"
[554] "cseguro_accidentes_personales_delta1"
[555] "cseguro_accidentes_personales_delta2"
[556] "ccaja_seguridad_delta1"
[557] "ccaja_seguridad_delta2"
[558] "cpayroll_trx_delta1"
[559] "cpayroll_trx_delta2"
[560] "mpayroll_delta1"
[561] "mpayroll_delta2"
[562] "mpayroll2_delta1"
[563] "mpayroll2_delta2"
[564] "cpayroll2_trx_delta1"
[565] "cpayroll2_trx_delta2"
[566] "ccuenta_debitos_automaticos_delta1"
[567] "ccuenta_debitos_automaticos_delta2"
[568] "mcuenta_debitos_automaticos_delta1"
[569] "mcuenta_debitos_automaticos_delta2"
[570] "ctarjeta_visa_debitos_automaticos_delta1"
[571] "ctarjeta_visa_debitos_automaticos_delta2"
[572] "mttarjeta_visa_debitos_automaticos_delta1"
[573] "mttarjeta_visa_debitos_automaticos_delta2"
[574] "ctarjeta_master_debitos_automaticos_delta1"
[575] "ctarjeta_master_debitos_automaticos_delta2"
[576] "mttarjeta_master_debitos_automaticos_delta1"
[577] "mttarjeta_master_debitos_automaticos_delta2"
[578] "cpagodeservicios_delta1"
[579] "cpagodeservicios_delta2"
[580] "mpagodeservicios_delta1"
[581] "mpagodeservicios_delta2"
[582] "cpagomiscuentas_delta1"
[583] "cpagomiscuentas_delta2"
[584] "mpagomiscuentas_delta1"
[585] "mpagomiscuentas_delta2"
[586] "ccajeros_propios_descuentos_delta1"
[587] "ccajeros_propios_descuentos_delta2"
[588] "mcajeros_propios_descuentos_delta1"
[589] "mcajeros_propios_descuentos_delta2"
[590] "ctarjeta_visa_descuentos_delta1"
[591] "ctarjeta_visa_descuentos_delta2"
[592] "mtarjeta_visa_descuentos_delta1"
[593] "mtarjeta_visa_descuentos_delta2"
[594] "ctarjeta_master_descuentos_delta1"
[595] "ctarjeta_master_descuentos_delta2"
[596] "mtarjeta_master_descuentos_delta1"
[597] "mtarjeta_master_descuentos_delta2"
[598] "ccomisiones_mantenimiento_delta1"
[599] "ccomisiones_mantenimiento_delta2"
[600] "mcomisiones_mantenimiento_delta1"
[601] "mcomisiones_mantenimiento_delta2"
[602] "ccomisiones_otras_delta1"
[603] "ccomisiones_otras_delta2"
[604] "mcomisiones_otras_delta1"
[605] "mcomisiones_otras_delta2"
[606] "cforex_delta1"
[607] "cforex_delta2"
[608] "cforex_buy_delta1"
[609] "cforex_buy_delta2"
[610] "mforex_buy_delta1"
[611] "mforex_buy_delta2"
[612] "cforex_sell_delta1"
[613] "cforex_sell_delta2"
[614] "mforex_sell_delta1"
[615] "mforex_sell_delta2"
[616] "ctransferencias_recibidas_delta1"
[617] "ctransferencias_recibidas_delta2"
[618] "mtransferencias_recibidas_delta1"
[619] "mtransferencias_recibidas_delta2"
[620] "ctransferencias_emitidas_delta1"
[621] "ctransferencias_emitidas_delta2"
[622] "mtransferencias_emitidas_delta1"
[623] "mtransferencias_emitidas_delta2"
[624] "cextraccion_autoservicio_delta1"
[625] "cextraccion_autoservicio_delta2"
[626] "mextraccion_autoservicio_delta1"
[627] "mextraccion_autoservicio_delta2"
[628] "ccheques_depositados_delta1"
[629] "ccheques_depositados_delta2"
[630] "mcheques_depositados_delta1"

### 9.7.2 Modelado

#### 9.7.2.1 Training Strategy

Se hace una estrategia de entrenamiento muy sencilla, tomando todos los meses posibles, SIN eliminar nada x pandemia ni por ningun otro motivo

* future = 202109  obviamente completo

* final_train =  [ 201901, 202107 ] sin undersampling de los CONTINUA

* training
   * testing = NO HAY
   * validation =  202107   completo, sin undersampling
   * training = [ 201901, 202105 ]  donde se consideran el 20% de los CONTINUA

In [18]:
PARAM$trainingstrategy$validate <- c(202107)

PARAM$trainingstrategy$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)

PARAM$trainingstrategy$training_pct <- 0.2


PARAM$trainingstrategy$positivos <- c( "BAJA+1", "BAJA+2")

In [19]:
# seteo la clase01   1={BAJA+1, BAJA+2}   0={CONTINUA}
dataset[, clase01 := ifelse( clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0 )]

In [20]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

In [21]:
# preparo para que se puede hacer undersampling de los CONTINUA
#  solamente por un tema de VELOCIDAD
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset[, azar:=runif(nrow(dataset))]

# undersampling de los CONTINUA
dataset[, fold_train :=  foto_mes %in%  PARAM$trainingstrategy$training &
    (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
     azar < PARAM$trainingstrategy$training_pct ) ]


if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

dtrain <- lgb.Dataset(
  data= data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
  label= dataset[fold_train == TRUE, clase01],
  free_raw_data= TRUE
)

In [22]:
# datos de validation
dvalidate <- lgb.Dataset(
  data= data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
  label= dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
  free_raw_data= TRUE
)

nrow(dvalidate)

[1] 164596

####  9.7.2.2. Hyperparameter Tuning

* Clase binaria que se optimiza :  positivos = [ BAJA+1, BAJA+2 ]

* Metrica que se optimiza **AUC** Area Under Curve de la  ROC Curve

es muy importante notar que intencionalmente  **NO** se está optimizando la funcion de ganancia del problema

* Cantidad de iteraciones inteligentes de la Optimizacion Bayesiana = **10**

* Parametros no default, fijos de LightGBM que no se optimizan
  * max_bin = 31 , Alienigenas Ancestrales contruyeron las pirámides y dejaron a la humanidad en un jeroglifico  *max_bin=31*
  * feature_fraction = 0.5  para poner algo que generalmente no falla
  * learning_rate = 0.03  para que aprenda lento

* Parametros que se optimizan en la Bayesian Optimization
  * num_leaves  [8, 256]
  * min_data_in_leaf  [8, 8192]

In [23]:
# paquetes necesarios para la Bayesian Optimization
if(!require("DiceKriging")) install.packages("DiceKriging")
require("DiceKriging")

if(!require("mlrMBO")) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers


Attaching package: ‘ParamHelpers’


The following object is masked from ‘package:R.utils’:

    isVector



Attaching package: ‘mlr’


The following objects are masked from ‘package:R.utils’:

    resample, setThreshold


Loading required package: smoof

Loading required package: checkmate


Attaching package: ‘checkmate’


The following object is masked from ‘package:DiceKriging’:

    checkNames


The following object is masked from ‘package:R.utils’:

    asInt



Attaching package: ‘smoof’


The following objects are masked from ‘package:R.oo’:

    getDescription, getName

Definición de la Bayesian Optimization
<br> Si se desea optimizar un hiperparámetro que esta como fijo, debe QUITARSE de param_fijos y agregarse a PARAM$hipeparametertuning$hs

In [24]:
# 40 es el minimo razonable,  un buen analista Sr aumentara este valor
PARAM$hipeparametertuning$num_interations <- 50

# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "auc",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  seed= PARAM$semilla_primigenia,
  extra_trees = FALSE,

  max_depth = -1L, # -1 significa no limitar,  por ahora lo dejo fijo
  min_gain_to_split = 0.0, # min_gain_to_split >= 0.0
  min_sum_hessian_in_leaf = 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1 = 0.0, # lambda_l1 >= 0.0
  lambda_l2 = 0.0, # lambda_l2 >= 0.0

  bagging_fraction = 1.0, # 0.0 < bagging_fraction <= 1.0
  pos_bagging_fraction = 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction = 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance = FALSE, #
  scale_pos_weight = 1.0, # scale_pos_weight > 0.0

  drop_rate = 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop = 50, # <=0 means no limit
  skip_drop = 0.5, # 0.0 <= skip_drop <= 1.0

  max_bin= 31,
  num_iterations= 2048,  # valor grande, lo limita early_stopping_rounds
  early_stopping_rounds= 200
)

Nuevos  pseudo hiperparámetros

*   leaf_size (0.0,  0.5]  es el   min_data_in_leaf / nrow(dataset)
*   coverage (0.0, 1.0]  se cumple   num_leaves =   coverage * (nrow(dataset)/min_data_in_leaf)

In [25]:
# Notar que se usan los pseudo hiperparametros "ratio"  leaf_size  y coverage
#  que luego terminan en  min_data_in_leaf y  num_leaves
#  de forma que sea invariante al tamaño del dataset

PARAM$hipeparametertuning$hs <- makeParamSet(
  makeNumericParam("learning_rate", lower = 0.02, upper = 0.3),
  makeNumericParam("feature_fraction", lower = 0.05, upper = 0.90),
  makeNumericParam("coverage", lower = 0.05, upper = 1.0), # nuevo
  makeNumericParam("leaf_size", lower = 0.001, upper = 0.2) # nuevo
)

Función "señora caja negra"  que es llamada para verificar la realidad por la Bayesian Optimization

In [26]:
# En  x llegan los parmaetros de la bayesiana
#  devuelve la AUC en validate del modelo entrenado
#  en el parametro x llegan los hiperparámetros que se estan optimizando

EstimarGanancia_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # hago la transformacion de leaf_size y  coverage
  if( "leaf_size"  %in% names(param_completo) &
      "coverage"  %in% names(param_completo)
  )
  {
    # primero defino el tamaño de las hojas
    param_completo$min_data_in_leaf <- pmax( 1,  round( nrow(dtrain) * param_completo$leaf_size )  )
    # luego la cantidad de hojas en funcion del valor anterior, el coverage, y la cantidad de registros
    param_completo$num_leaves <- pmin( 131072,
      pmax( 8,  round( ( param_completo$coverage * nrow( dtrain ) / param_completo$min_data_in_leaf ) ) ))
  }

  if( "leaf_size"  %in% names(param_completo) &
      !( "coverage"  %in% names(param_completo) )
  )
  {
    # primero defino el tamaño de las hojas
    param_completo$min_data_in_leaf <- pmax( 1,  round( nrow(dtrain) * param_completo$leaf_size )  )
  }


  # entreno LightGBM
  modelo_train <- lgb.train(
    data= dtrain,
    valids= list(valid = dvalidate),
    eval= "auc",
    param= param_completo,
    verbose= -100
  )

  # recupero la AUC en validation
  AUC <- modelo_train$record_evals$valid$auc$eval[[modelo_train$best_iter]]

  # esta es la forma de devolver un parametro extra
  attr(AUC, "extras") <- list("num_iterations"= modelo_train$best_iter)

  # hago espacio en la memoria
  rm(modelo_train)
  gc(full= TRUE, verbose= FALSE)

  message(format(Sys.time(), "%a %b %d %X %Y"), " AUC ", AUC)

  return(AUC)
}

seteo de la Bayesian Optimization (complejo)
<br> copiado y pegado de la documentación de la librería

In [27]:
configureMlr(show.learner.output = FALSE)

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo
obj.fun <- makeSingleObjectiveFunction(
    fn= EstimarGanancia_AUC_lightgbm, # la funcion que voy a maximizar
    minimize= FALSE, # estoy Maximizando AUC
    noisy= FALSE,
    par.set= PARAM$hipeparametertuning$hs,
    has.simple.signature= FALSE # paso los parametros en una lista
)

# cada 600 segundos guardo el resultado intermedio
ctrl <- makeMBOControl(
    save.on.disk.at.time= 600,
    save.file.path= "HT.RDATA"
)

# indico la cantidad de iteraciones que va a tener la Bayesian Optimization
ctrl <- setMBOControlTermination(
    ctrl,
    iters= PARAM$hipeparametertuning$num_interations  # cantidad de iteraciones inteligentes
)

# defino el método estandar para la creacion de los puntos iniciales
#   los "No Inteligentes"
ctrl <- setMBOControlInfill(ctrl, crit = makeMBOInfillCritEI())

# mas configuraciones
surr.km <- makeLearner(
    "regr.km",
    predict.type= "se",
    covtype= "matern3_2",
    control= list(trace = TRUE)
)

Corrida de la Bayesian Optimization,  aqui se hace el trabajo pesado
<br> por favor no se asuste con los warnings que pudieran aparecer

Si corrío a medias y llegó a las iteraciones inteligentes, en el archivo binario HT.RDATA quedó lo ya procesado y es utilizado para retomar la corrida desde lo último que llegó a grabar.

In [28]:
notificar(paste0("Arranca Bayesiana"))

In [29]:
# inicio la optimizacion bayesiana

#if (!file.exists("HT.RDATA")) {
 # bayesiana_salida <- mbo(obj.fun, learner= surr.km, control= ctrl)
#} else {
#  bayesiana_salida <- mboContinue("HT.RDATA") # retomo en caso que ya exista
#}
PARAM$out$lgbm$mejores_hiperparametros = list(
  learning_rate     = 0.0381405,
  feature_fraction  = 0.1293985,
  coverage          = 0.7132533,
  leaf_size         = 0.0125299
)

In [30]:
notificar(paste0("Fin Bayesiana"))

la bayesian optimization ha corrido, extraigo los mejores hiperparametros

### 9.7.3 Produccion

#### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

##### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización bayesiana

In [31]:
PARAM$trainingstrategy$final_train <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107
)

dataset[, fold_final_train := foto_mes %in% PARAM$trainingstrategy$final_train ]

# creo el dfinal_train en formato  LightGBM
dfinal_train <- lgb.Dataset(
  data= data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with= FALSE]),
  label= dataset[fold_final_train == TRUE, clase01],
  free_raw_data= TRUE
)

nrow( dfinal_train) # verifico el tamaño

[1] 4553136

##### Final Training Hyperparameters

In [32]:
# uno los parametros fijos y los mejores encontrados de los variables
fijos <- copy(PARAM$lgbm$param_fijos)

# quito lo que optimice en la Bayesian Optimization
fijos$num_iterations <- NULL
fijos$early_stopping_rounds <- NULL

# agrego a los hiperparametros fijos los que encontre con la Bayesian Optimization
param_final <- c(fijos, PARAM$out$lgbm$mejores_hiperparametros)

# hago la transformacion de leaf_size y  coverage
  if( "leaf_size"  %in% names(param_final) &
      "coverage"  %in% names(param_final)
  )
  {
    # primero defino el tamaño de las hojas
    param_final$min_data_in_leaf <- pmax( 1,  round( nrow(dtrain) * param_final$leaf_size )  )
    # luego la cantidad de hojas en funcion del valor anterior, el coverage, y la cantidad de registros
    param_final$num_leaves <- pmin( 131072,
      pmax( 8,  round( ( param_final$coverage * nrow( dtrain ) / param_final$min_data_in_leaf ) ) ))
  }

  if( "leaf_size"  %in% names(param_final) &
      !( "coverage"  %in% names(param_final) )
  )
  {
    # primero defino el tamaño de las hojas
    param_final$min_data_in_leaf <- pmax( 1,  round( nrow(dtrain) * param_final$leaf_size )  )
  }

In [33]:
param_final

$objective
[1] "binary"

$metric
[1] "auc"

$first_metric_only
[1] TRUE

$boost_from_average
[1] TRUE

$feature_pre_filter
[1] FALSE

$verbosity
[1] -100

$force_row_wise
[1] TRUE

$seed
[1] 888889

$extra_trees
[1] FALSE

$max_depth
[1] -1

$min_gain_to_split
[1] 0

$min_sum_hessian_in_leaf
[1] 0.001

$lambda_l1
[1] 0

$lambda_l2
[1] 0

$bagging_fraction
[1] 1

$pos_bagging_fraction
[1] 1

$neg_bagging_fraction
[1] 1

$is_unbalance
[1] FALSE

$scale_pos_weight
[1] 1

$drop_rate
[1] 0.1

$max_drop
[1] 50

$skip_drop
[1] 0.5

$max_bin
[1] 31

$learning_rate
[1] 0.0381405

$feature_fraction
[1] 0.1293985

$coverage
[1] 0.7132533

$leaf_size
[1] 0.0125299

$min_data_in_leaf
[1] 10952

$num_leaves
[1] 57

##### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [34]:
PARAM$FT$semillerio <- 20 # cantidad de semillas

In [35]:
if(!require("primes")) install.packages("primes")
require("primes")

Loading required package: primes

In [36]:
primos <- generate_primes(min = 100000, max = 1000000)
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
# me quedo con PARAM$semillerio  primos al azar
PARAM$FT$semillas <- sample(primos)[seq(PARAM$FT$semillerio)]

cat( PARAM$FT$semillas)

353473 307843 839879 440347 920743 800281 428471 440311 168449 718357 720991 961139 657197 408347 771073 910201 930089 723727 431369 794039

In [37]:
dir.create("modelos", showWarnings =FALSE)

primero <- TRUE
for( sem in PARAM$FT$semillas)
{
  nombre_arch <- paste0( "./modelos/modelo_", sem, ".txt")
  if( !file.exists(nombre_arch) )
  {
    param_final$seed <- sem

    set.seed(sem, kind = "L'Ecuyer-CMRG")
    final_model <- lgb.train(
      data= dfinal_train,
      param= param_final,
      verbose= -100
    )

    lgb.save(final_model, nombre_arch) # grabo el modelo"

    # grabo la primer importancia de variables
    #  Natalia : da lo mismo cual se guarda
    if( primero)
    {
      primero <- FALSE
      tb_importancia <- as.data.table(lgb.importance(final_model))
      archivo_importancia <- "impo.txt"

      fwrite( tb_importancia,
        file= archivo_importancia,
        sep= "\t"
      )
    }
 }
}

#### Scoring

Aplico el modelo final a los datos del futuro

In [38]:
PARAM$trainingstrategy$future <- c(202109)

dfuture <- dataset[ foto_mes %in% PARAM$trainingstrategy$future ]

In [39]:
# aplico final_model   a dfuture

tb_prediccion <- dfuture[, list(numero_de_cliente)]
tb_prediccion[, prob := 0]

datos_matrix <- data.matrix(dfuture[, campos_buenos, with= FALSE])


for( isem in seq(length(PARAM$FT$semillas)) )
{
   sem <- PARAM$FT$semillas[ isem ]
   nombre_arch <- paste0( "./modelos/modelo_", sem, ".txt")
   final_model <- lgb.load(nombre_arch)

   prediccion <- predict(
     final_model,
     datos_matrix
  )

  tb_prediccion[, paste0("prob_", isem) := prediccion]
  tb_prediccion[, prob := prob + prediccion]

  rm(final_model)
  rm(prediccion)
  gc(full = TRUE, verbose=FALSE)
}

rm( datos_matrix)
gc(full = TRUE, verbose=FALSE)

tb_prediccion[, prob := prob /length(PARAM$FT$semillas) ]

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells    2377465   127.0     4272162    228.2     4272162    228.2
Vcells 4602171746 35111.8 14280964083 108955.2 13981849973 106673.1

In [40]:
# veo que hay en tb_prediccion
tb_prediccion

       numero_de_cliente prob         prob_1       prob_2       prob_3
1      29183733          0.0009894114 0.0011153988 0.0008475177 0.0010259311
2      29184468          0.0007077104 0.0007843791 0.0006727618 0.0007044727
3      29185245          0.0161979934 0.0150737778 0.0182553658 0.0144054257
4      29186441          0.0014188433 0.0013636135 0.0014525411 0.0014638128
5      29186475          0.0013597307 0.0013918710 0.0014254755 0.0014201104
6      29187730          0.0006926581 0.0007944867 0.0007691947 0.0006314986
7      29187764          0.0008287496 0.0009484264 0.0007254958 0.0008371090
8      29187961          0.0018144689 0.0018058408 0.0020039140 0.0018246307
9      29189899          0.0013764305 0.0013423646 0.0014354713 0.0014397943
10     29189993          0.0021008271 0.0019805311 0.0018901355 0.0022815798
11     29190113          0.0010420380 0.0011048269 0.0010321791 0.0012479218
12     29192179          0.0027272296 0.0024968606 0.0023182383 0.0032132885
13     29193101          0.0017919467 0.0018494809 0.0016352264 0.0020689540
14     29193281          0.0013860181 0.0012680740 0.0013497298 0.0013297347
15     29193324          0.0055184461 0.0052656672 0.0050812561 0.0049673860
16     29195356          0.0130348366 0.0148345601 0.0124078030 0.0144580132
17     29195433          0.0006171185 0.0006358213 0.0005783011 0.0006580720
18     29196099          0.0030149284 0.0026014801 0.0028312392 0.0032510960
19     29196902          0.0017706997 0.0016602672 0.0019080483 0.0016570921
20     29198055          0.0007041171 0.0007819879 0.0007137697 0.0007297045
21     29198891          0.0025833905 0.0027689445 0.0034173259 0.0024753252
22     29199242          0.0053314373 0.0055932374 0.0046643260 0.0042495870
23     29200335          0.0007009553 0.0006571884 0.0006366282 0.0006470510
24     29200343          0.0021302399 0.0020509078 0.0020227781 0.0022843028
25     29200514          0.0053576685 0.0055819054 0.0058853035 0.0055150138
26     29200651          0.0067299906 0.0090986788 0.0084901835 0.0054691055
27     29200727          0.0018251442 0.0021019834 0.0016372562 0.0015573562
28     29200770          0.0006235598 0.0006221765 0.0006148784 0.0005997540
29     29200984          0.0020145415 0.0020497760 0.0021989262 0.0022255725
30     29201086          0.0008187893 0.0008982884 0.0007530592 0.0007931838
⋮      ⋮                 ⋮            ⋮            ⋮            ⋮
165064 187967614         0.011845790  0.011027388  0.012181282  0.012826843
165065 187969270         0.016055945  0.014484183  0.018308346  0.016509078
165066 187989740         0.017881111  0.017575512  0.019384039  0.018806649
165067 187999433         0.005760553  0.004589358  0.004534200  0.005594472
165068 188009390         0.016471008  0.014831038  0.018697857  0.017144141
165069 188009578         0.017121775  0.016694388  0.019054854  0.017421855
165070 188015094         0.005561189  0.005599336  0.005301022  0.006022293
165071 188017716         0.006163467  0.006645394  0.007835211  0.005733792
165072 188019279         0.028959319  0.026995965  0.022036085  0.025860383
165073 188031482         0.005396803  0.004901673  0.004963015  0.005542381
165074 188042080         0.016162194  0.014927898  0.018380898  0.016509078
165075 188054394         0.010004983  0.010439878  0.007637104  0.011039687
165076 188055368         0.029271567  0.025044522  0.046669490  0.039429025
165077 188057878         0.013011594  0.014776521  0.014228038  0.012548534
165078 188061679         0.006857130  0.007812683  0.006466730  0.006926919
165079 188062558         0.017245200  0.017170863  0.018966758  0.017610579
165080 188064497         0.011882254  0.011136641  0.012673490  0.012322500
165081 188071815         0.013024957  0.012467205  0.014197248  0.012505582
165082 188073113         0.020135478  0.019070150  0.020774322  0.019255514
165083 188074787         0.016185476  0.015118956  0.018380898  0.016509078
165084 188084847         0.002821868  0.003416271  0.002831033  0.002539794
165085 188096188         0.024487301  0.023964120  0.021588198  0.032578769
165086 188097537         0.016996647  0.017520790  0.018397715  0.017696205
165087 188100654         0.014817589  0.013954547  0.016707698  0.015970724
165088 188101739         0.015136003  0.013954547  0.017206447  0.015999420
165089 188115120         0.008785899  0.009249858  0.011224331  0.007357559
165090 188116871         0.003812306  0.004243538  0.004414808  0.004100670
165091 188122277         0.008026129  0.007360172  0.006061836  0.007703478
165092 188128903         0.016063115  0.015985991  0.018930147  0.016823015
165093 188136205         0.015857254  0.014375053  0.018380898  0.016509078
       prob_4       prob_5       prob_6       prob_7       prob_8       ⋯
1      0.0010998101 0.0009082978 0.0010309528 0.0009472633 0.0009155846 ⋯
2      0.0007434591 0.0007694997 0.0006630323 0.0006368822 0.0007025585 ⋯
3      0.0157107199 0.0130977088 0.0192412208 0.0111017709 0.0196017917 ⋯
4      0.0013411751 0.0015131581 0.0013164584 0.0012792827 0.0013838009 ⋯
5      0.0013007763 0.0013397376 0.0014289155 0.0011809631 0.0013717553 ⋯
6      0.0007266735 0.0006244293 0.0007392568 0.0006317137 0.0006237723 ⋯
7      0.0008959384 0.0009166718 0.0009027779 0.0007596059 0.0007118049 ⋯
8      0.0016349325 0.0020499894 0.0018018944 0.0017296904 0.0020090984 ⋯
9      0.0014735014 0.0014227067 0.0012605177 0.0013194534 0.0013831431 ⋯
10     0.0020217783 0.0024441943 0.0018825471 0.0022145307 0.0019431211 ⋯
11     0.0010604579 0.0011671244 0.0011090411 0.0010647004 0.0011382015 ⋯
12     0.0028193702 0.0029533050 0.0023478750 0.0028890834 0.0021130364 ⋯
13     0.0020283798 0.0018371747 0.0015509909 0.0015511408 0.0015827668 ⋯
14     0.0013331359 0.0014328080 0.0013208179 0.0014205587 0.0015335362 ⋯
15     0.0050879318 0.0056571750 0.0059207995 0.0044946461 0.0069727893 ⋯
16     0.0126896246 0.0115348059 0.0122797384 0.0136754285 0.0135992489 ⋯
17     0.0005978604 0.0006132589 0.0006066966 0.0006039850 0.0006010161 ⋯
18     0.0028596830 0.0029704454 0.0024566879 0.0028206379 0.0026201563 ⋯
19     0.0019840839 0.0016032679 0.0029083192 0.0014852342 0.0020705774 ⋯
20     0.0007258510 0.0007356304 0.0006700145 0.0006631560 0.0006652865 ⋯
21     0.0021520236 0.0024164020 0.0024178016 0.0024387232 0.0027426174 ⋯
22     0.0051789807 0.0071084057 0.0046395421 0.0054019988 0.0059712726 ⋯
23     0.0006359292 0.0007229319 0.0007211576 0.0007690729 0.0007913572 ⋯
24     0.0019339354 0.0023466847 0.0018457779 0.0018264419 0.0018018234 ⋯
25     0.0045818830 0.0071855680 0.0040908102 0.0053858152 0.0039623216 ⋯
26     0.0055081523 0.0054890047 0.0079883904 0.0071470103 0.0082104832 ⋯
27     0.0017808987 0.0020621198 0.0018547755 0.0017367513 0.0019509368 ⋯
28     0.0005800584 0.0007331999 0.0006422171 0.0005953026 0.0006495544 ⋯
29     0.0017502314 0.0022030013 0.0017169343 0.0018400410 0.0018600515 ⋯
30     0.0009083962 0.0008387454 0.0008213139 0.0008155103 0.0008482540 ⋯
⋮      ⋮            ⋮            ⋮            ⋮            ⋮            ⋱
165064 0.010911693  0.010294733  0.010572341  0.011319785  0.009574029  ⋯
165065 0.017727038  0.018498883  0.013555878  0.015849316  0.015428694  ⋯
165066 0.018592276  0.018497876  0.014306518  0.017313281  0.017841231  ⋯
165067 0.006404308  0.005719531  0.004681664  0.005687845  0.004390738  ⋯
165068 0.018632856  0.018925952  0.013973357  0.016076458  0.016168599  ⋯
165069 0.018385232  0.018002257  0.013654786  0.016017794  0.015790471  ⋯
165070 0.005364329  0.005587965  0.005324408  0.005156382  0.004877958  ⋯
165071 0.006857047  0.004535700  0.004652865  0.006222890  0.006064198  ⋯
165072 0.018555349  0.023501517  0.019208723  0.020207797  0.024518747  ⋯
165073 0.004857554  0.005414497  0.005148095  0.004568823  0.004859199  ⋯
165074 0.017727038  0.018447395  0.013555878  0.016105691  0.015460117  ⋯
165075 0.009795357  0.009413079  0.009257731  0.010817743  0.008824374  ⋯
165076 0.029600034  0.030138631  0.031360683  0.033279356  0.020139967  ⋯
165077 0.015103110  0.012755809  0.009912431  0.012539438  0.011584068  ⋯
165078 0.006115246  0.006519299  0.006532240  0.006074956  0.006541308  ⋯
165079 0.018910154  0.018214141  0.014137699  0.016017794  0.016048954  ⋯
165080 0.010756433  0.010011440  0.011191647  0.011315978  0.010436434  ⋯
165081 0.014043867  0.013927235  0.010779134  0.013440687  0.013507093  ⋯
165082 0.022061927  0.021988546  0.017754175  0.018921637  0.018197432  ⋯
165083 0.017727038  0.018232848  0.013749914  0.016105691  0.015460117  ⋯
165084 0.002941996  0.003089493  0.002807227  0.002691812  0.002564581  ⋯
165085 0.025466275  0.023583430  0.019315713  0.022721397  0.019707596  ⋯
165086 0.018625350  0.017675720  0.014575406  0.016533616  0.016855636  ⋯
165087 0.016485497  0.016773772  0.012858075  0.013821496  0.013543393  ⋯
165088 0.016676380  0.017318278  0.013093272  0.014558206  0.015316718  ⋯
165089 0.008268063  0.007921126  0.009478403  0.007156878  0.008660250  ⋯
165090 0.002956445  0.003787447  0.004639186  0.003222503  0.004564173  ⋯
165091 0.008860370  0.008370494  0.007105654  0.006822822  0.007138281  ⋯
165092 0.017518460  0.016186410  0.013766446  0.015119314  0.017069237  ⋯
165093 0.017544536  0.018232029  0.013250816  0.015392022  0.015316718  ⋯
       prob_11      prob_12      prob_13      prob_14      prob_15
1      0.0008746278 0.0010910115 0.0009419362 0.0010192711 0.0010115923
2      0.0007110671 0.0006298251 0.0006701545 0.0007619932 0.0006684155
3      0.0150464671 0.0265576662 0.0123541236 0.0170113977 0.0156607519
4      0.0014812488 0.0013991271 0.0015134022 0.0012684997 0.0013489826
5      0.0014282733 0.0013271459 0.0013349043 0.0013253858 0.0013686244
6      0.0006906000 0.0008164115 0.0006736287 0.0006223824 0.0007319140
7      0.0007495879 0.0008374466 0.0009074548 0.0007540524 0.0007461435
8      0.0015536812 0.0017769032 0.0018170678 0.0020665270 0.0017796447
9      0.0013069706 0.0013049827 0.0013231471 0.0014697128 0.0015179352
10     0.0018437853 0.0021639065 0.0023975387 0.0020905430 0.0022975075
11     0.0010579207 0.0010860303 0.0008819221 0.0009717010 0.0011818462
12     0.0028517241 0.0026615518 0.0029205731 0.0025922000 0.0028147727
13     0.0019879397 0.0017230494 0.0017610107 0.0016352540 0.0015947212
14     0.0013351460 0.0014863294 0.0012725537 0.0015921360 0.0015310074
15     0.0047502553 0.0050115127 0.0046605404 0.0065495901 0.0088421219
16     0.0168911206 0.0120943279 0.0113072428 0.0139162628 0.0144326872
17     0.0005730982 0.0006400321 0.0006622870 0.0006126707 0.0006013472
18     0.0033721012 0.0033251514 0.0031915018 0.0031501013 0.0028027451
19     0.0019693785 0.0015340081 0.0019708482 0.0017512342 0.0015560653
20     0.0006904208 0.0006948400 0.0006997231 0.0007315534 0.0007147212
21     0.0027833866 0.0026581451 0.0022915350 0.0031104440 0.0026579984
22     0.0062337686 0.0042519938 0.0043878204 0.0049376066 0.0046983644
23     0.0006515911 0.0007840058 0.0006722218 0.0006483031 0.0007666384
24     0.0020836534 0.0022986322 0.0020955410 0.0017470034 0.0018832264
25     0.0057318728 0.0050427637 0.0060271858 0.0038477487 0.0046822936
26     0.0056204248 0.0055288200 0.0064632260 0.0095113616 0.0065941697
27     0.0015686951 0.0017102385 0.0018958038 0.0023719504 0.0017528838
28     0.0006140757 0.0006202051 0.0006414938 0.0005840577 0.0006236139
29     0.0020879930 0.0019466193 0.0019892758 0.0018079877 0.0020056703
30     0.0007559399 0.0007545716 0.0007975310 0.0007472940 0.0007356255
⋮      ⋮            ⋮            ⋮            ⋮            ⋮
165064 0.012373524  0.012859935  0.012763134  0.010645493  0.011477662
165065 0.014811715  0.014084905  0.019128343  0.015629267  0.016243775
165066 0.017152626  0.016258705  0.020822898  0.019324803  0.018109461
165067 0.007398207  0.004856950  0.006480444  0.004566553  0.005227074
165068 0.015528751  0.014306538  0.019308029  0.015629267  0.016398264
165069 0.015611973  0.015113419  0.020542896  0.018010487  0.017339525
165070 0.005259069  0.006192676  0.005831994  0.005176584  0.004975449
165071 0.005933841  0.005856598  0.006609884  0.005830533  0.005361987
165072 0.048175522  0.036073308  0.022924125  0.020436184  0.040264055
165073 0.005753383  0.005203340  0.005637056  0.005096551  0.005556884
165074 0.014885244  0.014059385  0.019686846  0.015635895  0.016044700
165075 0.010806725  0.010078047  0.008342108  0.007795718  0.010370505
165076 0.025631715  0.020569589  0.037191934  0.020231140  0.020838724
165077 0.011494981  0.009933235  0.015244561  0.012870947  0.011068456
165078 0.007026961  0.007579141  0.007488911  0.005791029  0.006391489
165079 0.015440462  0.014879474  0.020845240  0.018189100  0.017345417
165080 0.012305224  0.012300995  0.012303022  0.010701823  0.012066335
165081 0.016382363  0.011631160  0.013363162  0.013588249  0.012585475
165082 0.019468022  0.015043954  0.024230193  0.017134570  0.020302229
165083 0.015050682  0.014059385  0.019686846  0.015635895  0.016197327
165084 0.002652665  0.002590658  0.002394281  0.002650653  0.002552274
165085 0.021429136  0.017600224  0.031635331  0.023306574  0.021347361
165086 0.016869600  0.015277052  0.020910447  0.018679086  0.017665069
165087 0.014194965  0.013665026  0.018329179  0.015250723  0.015323346
165088 0.014268397  0.013952884  0.018528919  0.015250723  0.016243775
165089 0.007552290  0.009082917  0.008326605  0.011798964  0.009021870
165090 0.003326873  0.004658675  0.003631327  0.003648616  0.004088621
165091 0.010091663  0.006492904  0.008990875  0.006650407  0.007894339
165092 0.016211800  0.014757788  0.017496683  0.017653741  0.017451009
165093 0.014665505  0.013927600  0.018907736  0.015079617  0.016044700
       prob_16      prob_17      prob_18      prob_19      prob_20
1      0.0008624382 0.0010119101 0.0011115833 0.0011991417 0.0010033311
2      0.0007991501 0.0006701555 0.0008041010 0.0006759223 0.0007530396
3      0.0160980503 0.0162037125 0.0167843148 0.0144127275 0.0137480864
4      0.0014957134 0.0016057632 0.0015818718 0.0014711547 0.0014466280
5      0.0013637857 0.0015140198 0.0015652120 0.0012607572 0.0014057652
6      0.0006411495 0.0007114997 0.0007348699 0.0006844796 0.0006362096
7      0.0008598169 0.0008398366 0.0007787993 0.0009458614 0.0008049294
8      0.0019280162 0.0016652209 0.0020784808 0.0016352139 0.0016505634
9      0.0012035413 0.0011976308 0.0015712904 0.0011485623 0.0015075654
10     0.0021997738 0.0020388194 0.0018434174 0.0021287097 0.0024177514
11     0.0008714981 0.0009560335 0.0010079433 0.0008902699 0.0010127746
12     0.0029273217 0.0029859346 0.0024703725 0.0028705244 0.0024756287
13     0.0017848907 0.0017414642 0.0017614929 0.0022453636 0.0016884278
14     0.0013007962 0.0013020724 0.0013030337 0.0013086301 0.0014296106
15     0.0067084110 0.0041147971 0.0064942599 0.0053739978 0.0041542895
16     0.0123951057 0.0128259691 0.0108299245 0.0115671531 0.0138353900
17     0.0006657884 0.0006098613 0.0006753176 0.0006075352 0.0006156777
18     0.0028983388 0.0035136980 0.0027068396 0.0033989179 0.0031309026
19     0.0012834534 0.0019236628 0.0014533750 0.0017533618 0.0019752090
20     0.0007334816 0.0006752034 0.0007575053 0.0006569616 0.0006862053
21     0.0022576845 0.0023500219 0.0027557788 0.0023741943 0.0025078519
22     0.0053067845 0.0048675871 0.0048971979 0.0055747185 0.0054747587
23     0.0007189048 0.0007029787 0.0007748002 0.0006543198 0.0006854269
24     0.0023488062 0.0025637060 0.0025028678 0.0023719990 0.0023556120
25     0.0052471463 0.0061480700 0.0053469499 0.0044715767 0.0063205724
26     0.0074132919 0.0059932039 0.0070736372 0.0046513578 0.0059939341
27     0.0019901587 0.0018424183 0.0018474138 0.0015937400 0.0018402272
28     0.0006410929 0.0006138944 0.0006160025 0.0006279854 0.0005643035
29     0.0021639525 0.0021916097 0.0021577423 0.0019740267 0.0025821139
30     0.0008352119 0.0008820960 0.0008692191 0.0008499455 0.0008409242
⋮      ⋮            ⋮            ⋮            ⋮            ⋮
165064 0.011719620  0.016079519  0.011259595  0.011964607  0.012887534
165065 0.016993640  0.015138034  0.014219976  0.016866407  0.014946655
165066 0.019873690  0.016362416  0.016806517  0.019627969  0.017166017
165067 0.008623033  0.006172917  0.004869730  0.006200302  0.006495834
165068 0.016802258  0.016376878  0.014219976  0.017318327  0.015383748
165069 0.017498981  0.015878080  0.018121795  0.018835770  0.016915894
165070 0.006295351  0.005504885  0.006184573  0.006360980  0.005867252
165071 0.006340407  0.006607698  0.008262184  0.005775388  0.006682023
165072 0.056710808  0.042141053  0.027376821  0.019568635  0.019688762
165073 0.006065892  0.005713038  0.004571816  0.004535167  0.006483508
165074 0.017188606  0.015374917  0.014219976  0.016866407  0.014946655
165075 0.012926580  0.012859766  0.007641192  0.011128688  0.010787397
165076 0.026409755  0.039107886  0.018444642  0.033235477  0.025294542
165077 0.016737248  0.013389312  0.011824561  0.013187915  0.012845436
165078 0.006933818  0.006874577  0.007395476  0.009014499  0.007260444
165079 0.017698156  0.015430261  0.018208549  0.018604245  0.016658905
165080 0.011350841  0.015943695  0.010866381  0.012478799  0.012723712
165081 0.011837513  0.012220252  0.012571339  0.012613627  0.014218540
165082 0.021519664  0.026823504  0.014810256  0.024776824  0.020086145
165083 0.016995067  0.015545493  0.014219976  0.016866407  0.014946655
165084 0.003396131  0.002882607  0.003171950  0.002900917  0.002984470
165085 0.026537690  0.032482230  0.018349152  0.031917863  0.023901602
165086 0.016691210  0.015231777  0.016353968  0.016884083  0.016470704
165087 0.014443455  0.013615645  0.013911768  0.013599963  0.014103137
165088 0.014443455  0.013765393  0.013911768  0.014058866  0.014103137
165089 0.008531966  0.007731887  0.009662678  0.007705195  0.007909742
165090 0.002947477  0.003416123  0.004863547  0.004038763  0.003113742
165091 0.009405436  0.008789256  0.007318242  0.007352304  0.009980041
165092 0.015922926  0.014192482  0.015763371  0.015667190  0.014859003
165093 0.016955446  0.015263552  0.013911768  0.016332549  0.014760482

In [41]:
# grabo las probabilidad del modelo
#  me va a ser util para hacer Ensembles de modelos
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

#### Kaggle Competition Submit

Genero las salidas y hago los submits a Kaggles

In [42]:
# genero archivos con los  "envios" mejores
# suba TODOS los archivos a Kaggle

PARAM$kaggle$competencia <- "data-mining-analista-sr-2025-a"
PARAM$kaggle$cortes <- seq(10000, 12000, by = 500)

# ordeno por probabilidad descendente
setorder(tb_prediccion, -prob)

dir.create("kaggle")

for (envios in PARAM$kaggle$cortes) {

  tb_prediccion[, Predicted := 0L] # seteo inicial a 0
  tb_prediccion[1:envios, Predicted := 1L] # marclo los primeros

  archivo_kaggle <- paste0(
    "./kaggle/KA",
    PARAM$experimento, "_",
    "s", length(PARAM$FT$semillas), "_",
    envios, ".csv")

  # grabo el archivo
  fwrite(tb_prediccion[, list(numero_de_cliente, Predicted)],
    file= archivo_kaggle,
    sep= ","
  )

  # subida a Kaggle, armo la linea de comando
  comando <- "kaggle competitions submit"
  competencia <- paste("-c", PARAM$kaggle$competencia)
  arch <- paste( "-f", archivo_kaggle)

  mensaje <- paste0("-m 'envios=", envios,
  "  semilla=", PARAM$semilla_primigenia,
    "'" )

  linea <- paste( comando, competencia, arch, mensaje)

  salida <- system(linea, intern=TRUE) # el submit a Kaggle
  cat(salida, "\n")
}

Successfully submitted to Data Mining, Analista Sr 2025A
Successfully submitted to Data Mining, Analista Sr 2025A
Successfully submitted to Data Mining, Analista Sr 2025A
Successfully submitted to Data Mining, Analista Sr 2025A
Successfully submitted to Data Mining, Analista Sr 2025A

In [43]:
# grabo los parametros
if( !require("yaml")) install.packages("yaml")
require("yaml")

write_yaml( PARAM, file="PARAM.yml")

Loading required package: yaml

In [44]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 24 22:43:49 2025"

In [45]:
notificar(paste0("Fin Notebook"))